### ISSUE TITLE
Consider introducing greenkeeper.io & snyk

### ISSUE THREAD

**Issue by ukmadlz** [Vonage/vonage-node-sdk#112]
The library currently has 17 devDependencies.

[Greenkeeper.io](https://greenkeeper.io) would allow or easier version bumping as it automates the process when new versions are added to npm.

[Snyk](https://snyk.io) does vulnerability checking, by introducing this you can check for dependencies that could be hazardous at the version implemented.

**Comment by mheap** [comment]
I've just started investigating this. Vulnerability scanning is handled by Github and @AlexLakatos and I are the recipients of any vulns. 

Greenkeeper looks nice, but there are some concerns around giving it write access to the repo so we're going to hold off now and stick with running `npm outdated` periodically. Stability is our main focus so as long as the library has no security issues, we'll likely only update when required for new features.
