### ISSUE TITLE
Voice API length_timer does not limit call duration

### ISSUE THREAD

**Issue by phil-andrews** [Vonage/vonage-node-sdk#122]
```
nexmoClient.calls.create({
    to: [{
      type: 'phone',
      number: toNumber
    }],
    from: {
      type: 'phone',
      number: fromNumber
    },
    answer_url: [answerURL],
    length_timer: 60,

  }, (err, res) => {

    if (err) {
      console.error(err)
    } else {
      console.log(res)
    }

  })
```

When dialing out using node I have been unable to get length_timer to end a call when set to any duration.

**Comment by phil-andrews** [comment]
Update on this: Via billing console I can say that it does seem to limit the time but the API does not kick back an event when it times out. This requires manually inserting timers into an automated application.

**Comment by leggetter** [comment]
@phil-andrews so you don't seem to be getting any [webhook call events](https://docs.nexmo.com/voice/voice-api/api-reference#cc_event_webhook) when the timeout takes place?

You should get a call status update to `completed`.

**Comment by phil-andrews** [comment]
After a couple thousand calls and plenty of time outs I do not believe that I am. It's possible that I'm not waiting long enough for it to come, ~90s. But even before I put that timer on I would have to manually reset a phone instance to handle a call that timed out. And during that period I waited 5-10 minutes a few times just to see if I'd get pinged.

On top of receiving the basic `completed` request, if it were possible, it would be very helpful to know that a call timed out via a `timeout` flag in the same request or in a subsequent request.

**Comment by manchuck** [comment]
Close due to inactivity
