### ISSUE TITLE
Same api as iOS client SDK

### ISSUE THREAD

**Issue by phukhanhlee** [Vonage/vonage-node-sdk#130]
https://docs.nexmo.com/verify/verify-sdk-for-iOS/advanced
I need to call logoutUser but i did't find same api in nodejs or in api document.
Please help !

**Comment by mheap** [comment]
@phukhanhlee The `node` client library is designed to talk to the Nexmo HTTP API. Unfortunately it provides different functionality to our `verify-sdk` which is only available for `iOS` and `Android`
