### ISSUE TITLE
Add private key support

### ISSUE THREAD

**Issue by adambutler** [Vonage/vonage-node-sdk#131]
Currently the nexmo-node library takes the private key as a path, this presents an issue in certain scenarios where the private key is to not be checked into version control; for example open source projects.

If for instance using hosting such as Heroku your application would need to:

1. Read the private key from the environment.
2. Write the private key to disk
3. Initialize `Nexmo` with the the private key path.

If the library were to support providing the private key itself then step 1 & 2 could could be avoided.

**Comment by leggetter** [comment]
It also supports a string. Could be that the docs just need updating.
