### ISSUE TITLE
Nexmo recording url return null !

### ISSUE THREAD

**Issue by phukhanhlee** [Vonage/vonage-node-sdk#132]
Please help !!!!
My app use nexmo for recording voice call. It works great before. But now we can't get record url

Here is my response JSON
*** Recording... ***
{ start_time: '2017-05-26T08:16:43Z',
recording_url: '',
size: 0,
recording_uuid: 'd8c75dcc-8a8d-4fb7-9d6e-527d5a435547',
end_time: '2017-05-26T08:16:53Z',
conversation_uuid: 'CON-e041a484-4d0b-4b79-bf12-8f0a7568dc92' }

Now every call return record url is null.

**Comment by leggetter** [comment]
This is being handled via Nexmo Support.
