### ISSUE TITLE
Getting an http 400 error code when executing nexmo.calls.talk.start

### ISSUE THREAD

**Issue by marcelgoya** [Vonage/vonage-node-sdk#133]
I'm running nexmo.calls.talk.start twice on the same callId. The first run works fine but I'm getting this error message when I'm running it a second or third time:

`{ body:
   { type: 400,
     title: 'Bad Request',
     invalid_parameters: [ [Object] ] },
  headers:
   { 'content-disposition': 'attachment; filename="api.txt"',
     'content-type': 'application/json',
     date: 'Tue, 30 May 2017 07:44:41 GMT',
     server: 'nginx',
     'strict-transport-security': 'max-age=31536000; includeSubdomains',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-nexmo-trace-id': '7b36726abe0bbc35f964861b22a941f9',
     'x-xss-protection': '1; mode=block;',
     'content-length': '83',
     connection: 'close' },
  statusCode: 400 }
{ Error: Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 189.99718963797204 second(s). Required at least: 191 second(s).
    at ClientDuplexStream._emitStatusIfDone (/Users/marcel/Documents/Web/lingusocial-backend-translator/node_modules/grpc/src/node/src/client.js:201:19)
    at ClientDuplexStream._receiveStatus (/Users/marcel/Documents/Web/lingusocial-backend-translator/node_modules/grpc/src/node/src/client.js:180:8)
    at /Users/marcel/Documents/Web/lingusocial-backend-translator/node_modules/grpc/src/node/src/client.js:649:14
  code: 3,
  metadata: Metadata { _internal_repr: { 'content-disposition': [Object] } } }`

The call id is the same but the text is different. It would be great if you could point me into the right direction. Thanks

**Comment by leggetter** [comment]
@marcelgoya - I've just pinged the engineering team that handle this to see if they can shed some light. Hopefully `Client GRPC deadline too short. Should be at least: 3 * audio-duration + 5 seconds. Current deadline is: 189.99718963797204 second(s). Required at least: 191 second(s).` helps identify the cause/problem.

**Comment by marcelgoya** [comment]
@leggetter Thanks for forwarding this. I think you can ignore the GRPC error message because it's not related to the actual problem but a speech recognition error message.

**Comment by leggetter** [comment]
@marcelgoya is it possible to replicate and expand the `invalid_parameters` property?

**Comment by marcelgoya** [comment]
@leggetter nope, not in my console. Basically, it happens no matter what text I feed him after the first execution of the start function.

**Comment by marcelgoya** [comment]
Alright, I was able to pin this one down. I'm making two voice calls with different call id's. Running the talk or stream cmd on the first call works fine but not on the second one. I've tripled checked that the call id's are correct, so I assume it might be something about the JWT token?

**Comment by leggetter** [comment]
@marcelgoya I need to put some sample code together to replicate. Shouldn't take too long.

If you have an example, please share. Otherwise I'll aim to get this tested on Monday. Is that okay?

**Comment by marcelgoya** [comment]
@leggetter Sure, I'll post an example tomorrow morning.

**Comment by marcelgoya** [comment]
@leggetter  Alright, after going through my call events, I've noticed that every time when I'm calling my phone number, the call status is changed to machine for whatever weird reason. Could this be a reason while I'm unable to use the tts command for example?

**Comment by marcelgoya** [comment]
@leggetter Ok, that was indeed the reason why it didn't work. Just did a test call where it didn't change to answer_machine and it worked.

**Comment by leggetter** [comment]
@marcelgoya - yes, you can only `talk` or `stream` to an active call.

**Comment by leggetter** [comment]
You can determine an active call by the events to the `event_url`. See the `answered` state https://docs.nexmo.com/voice/voice-api/handle-call-state

**Comment by marcelgoya** [comment]
@leggetter Is there any way to disable the answer machine detection? I'm asking because I had it dozens of times where I picked up the call and it still detected it.

**Comment by leggetter** [comment]
Machine detection is off by default. It's only on if you use the `machineDetection` attribute. Are you using that in your NCCO?

**Comment by marcelgoya** [comment]
@leggetter  Nope, I'm not using it. It's funny because the problem solved itself yesterday evening and it's working fine now. So I'm going to close this one. Thanks for your help!
