### ISSUE TITLE
Call issue in sendSMS function

### ISSUE THREAD

**Issue by coreyarch1234** [Vonage/vonage-node-sdk#145]
I clicked on the declaration file for message.js, and I couldn't find a way to receive a callback after:

nexmo.message.sendSms(from, to, text). The docs have no information. It just states that you can include a callback as such:

nexmo.message.sendSms(from, to, text, callback). But there is no explanation of what and how to use that callback.

Eric and Chris helped me at the Tech Crunch Disrupt hackathon and the solution we found was to set a timer for 3 seconds between each message. Here is a snippet:

``` javascript
setInterval(function()
{
    var nextNumber = removeNumber(numbers)
    nexmo.message.sendSms(from , to, text);
}, 3000);
```

**Comment by ericgiannini** [comment]
Part of the problem is the issue addressed in the following [blog](https://help.nexmo.com/hc/en-us/articles/204017023-USA-Features-Restrictions ): 

> You may send a maximum of 1 SMS per second and per virtual number in the US and Canada due to local carriers regulations. If you send messages more quickly, the message(s) will be rejected. If you require higher throughput, you can purchase more numbers and spread your traffic across your numbers. E.g. 10 numbers = 10 SMS per second.

**Comment by AlexLakatos** [comment]
Hi @coreyarch1234,

`sendSms` takes an optional `callback` parameter, and that gets called at the end of the execution with `(error, response)`. If you want to add your own parameter, you'll have to `.bind()` that to the callback.

Here is a working example:
```
function smsCallback(err, response){
  console.log("error:", err);
  console.log("response:", response);
  console.log("my parameter:", this.myParam)
}

nexmo.message.sendSms(from, to, "message", smsCallback.bind({myParam: "it works!"}));
```

**Comment by lornajane** [comment]
Looks like this was answered, closing (but re-open if you still need help)
