### ISSUE TITLE
Websocket Connection closing randomly during call

### ISSUE THREAD

**Issue by cakedan** [Vonage/vonage-node-sdk#150]
Currently, I send in audio at the correct format: 640 bytes, 16 bit, 16000 Sample Rate (16kHz), 20ms Frame Duration, and 1 channel (mono). The call goes on completely normal, audio is received both on my end and the phone's end normally, but randomly the phone's end would hang up the phone call and disconnect from the Websocket server.

My Websocket server I'm using is based off of https://github.com/nexmo-community/ws-phone .

**Comment by mheap** [comment]
Is there a repo that I could clone and run to try and reproduce this issue @cakedan? Alternatively, could you share the audio file that you're streaming in to the websocket?

When you say that the call randomly ends, do you mean that it happens on every call after a random amount of time, or that it only happens on some calls?

**Comment by lornajane** [comment]
Closed due to inactivity  (but re-open if you have more info for us)
