### ISSUE TITLE
[Enhancement] Add a call example/docs modifying local router configuration with DMZ

### ISSUE THREAD

**Issue by AlvaroBernalG** [Vonage/vonage-node-sdk#151]
Hello good people of nexmo-node,

Home router configuration is becoming easier and easier to use. I think it would be a good idea to add an example of assigning a DMZ  to a local machine IP. That way you eliminate the need of using Ngrok, reduce the code size/configuration of some of the examples thus making them easier to understand. 

I volunteer to do the PR if maintainer agrees.

Regards,
Alvaro

**Comment by mheap** [comment]
Hi @AlvaroBernalG,

Those that are capable of using a DMZ likely already know how to configure it, and there are so many different routers that documenting them all seems unfeasible. For this reason, I think that we should keep `ngrok` as the solution for exposing local servers at this time
