### ISSUE TITLE
NCCO

### ISSUE THREAD

**Issue by pmaxim** [Vonage/vonage-node-sdk#158]
Thank you. JWT  key works perfectly.
I get a call, but I can not hear the sound.
My   NCCO - https://riddler.serverpipe.com/api/apinexmo/nexmovoice
I'm getting a request for this address, but there is no sound.
Thanks

**Comment by DylanGauthier** [comment]
Hi @pmaxim , it looks like we can't see what your NCCO looks like, your link looks dead.
Can you please provide another link so we can investigate further ?

Thanks,

Dylan

**Comment by mheap** [comment]
Any update on this @pmaxim?

**Comment by lornajane** [comment]
Closed due to inactivity
