### ISSUE TITLE
problam on ver 0.6

### ISSUE THREAD

**Issue by dorshay6** [Vonage/vonage-node-sdk#16]
when i tried to update to version 0.6 the first sms worked fine but all the other send to the same number of the first sms and with the option i provided in the end of the sms text.

**Comment by pvela** [comment]
could you please turn the debugon and paste the output.

The 4th parameter to the initialize function set the debug. for ex :
nexmo.initialize("key","secret","https",true);

Also if possible paste the the code that you are using to send SMS message using the previously initialized nexmo object.

**Comment by ashoksahoo** [comment]
+1
`sending message from XXXXXXXXX to +917093245428 with message Don't pay for SMS anymore. Download Mara Messenger to enjoy cool features like free outgoing SMS, doodle, chat & lots more.
sent by ashok via Mara Messenger
http://goo.gl/vKni5V
{ host: 'rest.nexmo.com',
  port: 80,
  path: '/sms/json?from=XXXXXXXXXX&to=%2B917093245428&text=Don\'t%20pay%20for%20SMS%20anymore.%20Download%20Mara%20Messenger%20to%20enjoy%20cool%20features%20like%20free%20outgoing%20SMS%2C%20doodle%2C%20chat%20%26%20lots%20more.%0Asent%20by%20ashok%20via%20Mara%20Messenger%0Ahttp%3A%2F%2Fgoo.gl%2FvKni5V&api_key=XXXXXXXXX&api_secret=XXXXXXX',
  method: 'POST',
  headers: 
   { 'Content-Type': 'application/x-www-form-urlencoded',
     accept: 'application/json',
     'Content-Length': 0 } }
POST /MaraChat/api/sendInviteSMS 200 111ms - 97b
response ended
sending message from XXXXXXXXX to +917093245428 with message Don't pay for SMS anymore. Download Mara Messenger to enjoy cool features like free outgoing SMS, doodle, chat & lots more.
sent by ashok via Mara Messenger
http://goo.gl/vKni5V
{ host: 'rest.nexmo.com',
  port: 80,
  path: '/sms/json?from=XXXXXXXXXX&to=%2B917093245428&text=Don\'t%20pay%20for%20SMS%20anymore.%20Download%20Mara%20Messenger%20to%20enjoy%20cool%20features%20like%20free%20outgoing%20SMS%2C%20doodle%2C%20chat%20%26%20lots%20more.%0Asent%20by%20ashok%20via%20Mara%20Messenger%0Ahttp%3A%2F%2Fgoo.gl%2FvKni5V?from=XXXXXXXXXX&to=%2B917093245428&text=Don\'t%20pay%20for%20SMS%20anymore.%20Download%20Mara%20Messenger%20to%20enjoy%20cool%20features%20like%20free%20outgoing%20SMS%2C%20doodle%2C%20chat%20%26%20lots%20more.%0Asent%20by%20ashok%20via%20Mara%20Messenger%0Ahttp%3A%2F%2Fgoo.gl%2FvKni5V&api_key=XXXXXXXX&api_secret=XXXXXXX',
  method: 'POST',
  headers: 
   { 'Content-Type': 'application/x-www-form-urlencoded',
     accept: 'application/json',
     'Content-Length': 0 } }
POST /MaraChat/api/sendInviteSMS 200 33ms - 97b
response ended`

**Comment by ashoksahoo** [comment]
`var path = msgpath;` on line 136 breaks it.
This is a shallow copy which breaks the API path..A deep copy should work..

**Comment by pvela** [comment]
This issue is fixed in 0.6.2 release.
