### ISSUE TITLE
Dialing out to <phone>#<confernece id>

### ISSUE THREAD

**Issue by hgezim** [Vonage/vonage-node-sdk#173]
Hi,

I'm trying to dial using tel: protocol into conference bridges where the final number will end up like so: <phone number>#<conference id> however, using `nexmo.calls.create` I get this error explanation: `invalid_parameters=[reason=can contain up to 15 digits prefixed with +, name=number]`:

```
nexmo.calls.create({
  to: [{
    type: 'phone',
    number: '+14156550001#193505289'
  }],
...
```

How, do I dial number like the `tel:` protocol does?

**Comment by mheap** [comment]
Hey @hgezim, sorry for the delay. We've been taking it easy over the holiday break!

I'm happy to say that we do support dialing in to conference bridges via `dtmfAnswer` like so:

```
nexmo.calls.create({
  to: [{
    type: 'phone',
    number: '+14156550001',
    dtmfAnswer: '193505289'
  }],
```

Give it a go and let us know if you need anything else
