### ISSUE TITLE
Getting this error using nexmo npm.

### ISSUE THREAD

**Issue by Shery11** [Vonage/vonage-node-sdk#175]
{
        "code": "ENOTFOUND",
        "errno": "ENOTFOUND",
        "syscall": "getaddrinfo",
        "hostname": "rest.nexmo.com",
        "host": "rest.nexmo.com",
        "port": 443
    }

Please let me know what the issue is i need to deliver.

**Comment by mheap** [comment]
Hi @Shery11,

It looks as though the machine you're running on can not connect to http://rest.nexmo.com - could you try visiting that URL without the library and let us know what happens?

**Comment by mheap** [comment]
It looks as though this was an environment issue (https://stackoverflow.com/questions/48010920/getting-error-from-server-using-nexmo-npm-package-to-send-sms)

Please let us know if you have any more issues
