### ISSUE TITLE
Security vulnerability in the hoek module, please update the jsonwebtoken module

### ISSUE THREAD

**Issue by papandreou** [Vonage/vonage-node-sdk#179]
A security vulnerability advisory has been issued for the hoek module: https://nodesecurity.io/advisories/566

Hoek is an indirect dependency of nexmo via jsonwebtoken (^7.1.9) -> joi (^6.10.1).

Luckily, jsonwebtoken [removed the joi dependency in 8.0.0](https://github.com/auth0/node-jsonwebtoken/blob/7b0a010e8a8ede7b2d31a702cf4fbab1cfc774b7/CHANGELOG.md#800---2017-09-06), so it seems like it's just a matter of updating to jsonwebtoken 8.x. The [list of breaking changes in version 8](https://github.com/auth0/node-jsonwebtoken/wiki/Migration-Notes:-v7-to-v8) doesn't look too worrying.

**Comment by ralphkocher** [comment]
Theres also the used request API effected:

nexmo@2.2.0 > request@2.83.0

**Comment by papandreou** [comment]
@mheap, looks like you addressed this in 04fbf96dfd4941ecd6bbe819cbda175bb7c47b8c, thanks! Will there be a new (not pre)release soon?

**Comment by mheap** [comment]
@papandreou 2.2.1 has just been released via NPM. Thanks for reporting, and apologies for the delay
