### ISSUE TITLE
Using nexmo sandbox!

### ISSUE THREAD

**Issue by romain10009** [Vonage/vonage-node-sdk#18]
Hi, is there a way to make the request of the library go to 
http://rest-sandbox.nexmo.com ?
I didn't see any mention about this. But in test environement i need to try out my logic before making actual requests.

**Comment by romain10009** [comment]
ok i'm branching out. I will do some testing and contribute.

**Comment by romain10009** [comment]
after some tests, it looks that nexmo has very poor support (doesnt care?) about their sandbox. It's impossible to buy a "sandbox" phone number. So I stopped developpement and simply created another account for my testing environment.

**Comment by ghost** [comment]
Our sandbox was in the "Labs" (experimental) section of our site before, so there were features still being tweaked. Right now it's been moved to the main docs and we are ensuring that is fully operational.
Please have a look here:
https://docs.nexmo.com/api-ref/nexmo-sandbox
We'll make sure to promptly fix any issues you might encounter!

**Comment by leggetter** [comment]
Nexmo no longer offer a Sandbox.

**Comment by quinncomendant** [comment]
@avl055 I noticed the link you gave https://docs.nexmo.com/api-ref/nexmo-sandbox just redirects to https://docs.nexmo.com/. I can't find any docs on how to test Nexmo. @leggetter says Nexmo no longer offers a Sandbox. I'm developing an app in Mexico that needs to use virtual numbers, and here they cost $12/month. For testing, it's not reasonable to spend such money for each num needed. Please tell me there is a way. =(

**Comment by xbugster** [comment]
Nexmo probably worst company that only cares to earn money, but not provide any reliable tech support to their customers. Such as no test/dev/staging/sandbox environment, for tests you have to purchase number and brainfuck about how to test your integration with their services, how your QA will test in QA Environment, when your QA envs point to QA sms/mailing service and other services.
They don't give a fuck about you.

**Comment by leggetter** [comment]
@quinncomendant We're working on ensuring that our APIs have definitions (likely in Swagger/OpenAPI Specification) that can then be used to generate your own sandbox. This removes the need for an integration into any form of 3rd party service that is outside of your testing environment.

We're presently looking to hire an API Design Lead to join the DevRel team to help with this effort.

If you'd like some credit to help with your testing please drop me an email with your API Key - leggetter@nexmo.com

**Comment by Braunson** [comment]
#BringBackTheSandbox #Testing

**Comment by lornajane** [comment]
@Braunson sorry, Nexmo does not have the sandbox but if you need some credit to test something, please let us know on devrel@nexmo.com what you're working on and your API key and we'll sort something out.
