### ISSUE TITLE
React project error

### ISSUE THREAD

**Issue by thesubway** [Vonage/vonage-node-sdk#181]
Reproduce:
-npm install nexmo
-npm start
Can't resolve 'dns' in 'project_directory/node_modules/isemail/lib'

**Comment by AlexLakatos** [comment]
Hi @thesubway,

Are you trying to use the `nexmo` node package on the front-end with React? It's not supposed to work in the browser, it's intended to be run in a Node server environment.

And it looks like isemail is erroring out and not nexmo. Can you give me more specifics about the code you're trying to run?

Cheers,
Alex

**Comment by thesubway** [comment]
I tried on a brand new react project, and it comes up only after I try to import Nexmo. So it seems the isemail error comes with nexmo (probably a dependency).
But yeah thanks, I should try running it on the back-end instead.
