### ISSUE TITLE
Play audio nexmo node

### ISSUE THREAD

**Issue by axchanda** [Vonage/vonage-node-sdk#183]

**Comment by mheap** [comment]
Hi @axchanda,

We use Amazon Polly as our text to speech engine here at Nexmo. If you'd like to play text in to a call, you can use the `nexmo.calls.talk.start` method - https://github.com/Nexmo/nexmo-node#play-synthesized-text-in-a-call

If that's not suitable, let us know and we can take a look at playing text from Polly in to a websocket

**Comment by axchanda** [comment]
Hi @mheap ,

Thanks for your response. But I am trying to acheive text-to-speech through websockets only. Because this will be real-time and also frequent shifts between AI and tts stt happens. So kindly help me for websockets. Your help will be so much appreciated.

Amazon Polly can be changed from the project but we need a text-to-speech at the websocket for sure.

**Comment by mheap** [comment]
@axchanda I'll be able to take a look later this week. Is the source code available for me to try and run?

**Comment by axchanda** [comment]
@mheap  I will send them in an hour. Also please suggest the best way to work out an AI bot with Nexmo. I tried your Lex connector but the speech was not recognized with the chatbot. So, had to shift to Google for stt engine. After AI processing, I need to send the text as audio into the websocket. Remeber there will be mulitple clients having their own conversations going on, so please make a note on that. Thanks for your help!

**Comment by axchanda** [comment]
[nexmo-tts-polly-websocket.zip](https://github.com/Nexmo/nexmo-node/files/1873560/nexmo-tts-polly-websocket.zip)

Please find the attachment @mheap . Sincere thanks for helping me. Just comment the methods one-by-one in the main code and insert aws creditinals. Thanks!

**Comment by axchanda** [comment]
@mheap Beg you to process this as soon as possible, because I may need to show a demo on this day-after-tomorrow. Sorry for the rush. Please!

**Comment by mheap** [comment]
@axchanda I found the issue! There were two things:

1. You were making the call to Polly inside `connection.on('message')`. This means that for every frame of audio data from the call you were making a request to Polly. Your code should be inside `on('connect')` not `on('message')`.

2. The audio buffer for websockets won't accept a full PCM file at a time. The data needs chunking up and sending piece by piece like so:

```node
const chunks = require('buffer-chunks')
Polly.synthesizeSpeech(params, (err, data) => {
    const parts = chunks(data.AudioStream, 640);
    for (let i in parts) {
        connection.sendBytes(parts[i]);
    }
});
```

You'll also need to `npm install buffer-chunks`

**Comment by axchanda** [comment]
@mheap Thanks for your answer. But slight differences in your answers:- 

1. I want to create a bot that responds to each and every message, may be not audio frame. So, inside the on('connect') the code can run only once during connection. But I want to run diff text as per the user input through the socket after speech recognition repeatedly. How to do that?
2. Thanks for that. Will try and tell you the result.

Please solve my first issue. That is my requirement. Thanks for this helping till this stage though!

**Comment by mheap** [comment]
@axchanda There's nowhere in your code that handles speech recognition. You will need to connect the websocket audio (`on('message')`) to a transcription service, then use `synthesizeSpeech` in the callback from the transcription based on the text

**Comment by mheap** [comment]
@axchanda Unfortunately I am unable to help build your solution for you. The original issue (playing PCM audio from Polly in to a websocket) has been solved

For realtime transcription, you may find https://github.com/nexmo-community/voice-google-speechtotext useful
