### ISSUE TITLE
Get the verification code generated for a verify request

### ISSUE THREAD

**Issue by varungupta85** [Vonage/vonage-node-sdk#184]
Is there a way to know the verification code generated by Nexmo for a verify request. My use case is that sometimes, users are not receiving the code by SMS even though Nexmo thinks that it has sent the code via SMS. In such cases, I want to resend the code to such users using the SMS API or some other service. Since Nexmo has generated the code, I should be able to complete second part of the verification using the request_id and the correct code.

**Comment by AlexLakatos** [comment]
Hi,
You can't get the code generated or complete the second part yourself with the request_id and the code, that wouldn't be very secure.

There are a few options you might want to try:
 - Verify re-sends the code for you though, and you can force the next resend
 - cancel the Verify request and make a new one, you're only paying for successful verification, so you won't get charged for the first
 - you can also look at tweaking the timers or manually advancing through the SMS retry and TTS. If the `pin_expiry` has been reached by the time the `next_event_wait` comes around it will generate a new pin, if not it sends the same pin. For example using `pin_expiry` of 300 seconds and next event wait of 60 seconds means you will get the same pin SMS1 at T0, SMS2 at T+60,  TTS at T+120 and then still have 2 more minutes to verify the pin after that. You can check the docs for that [here](https://developer.nexmo.com/api/verify#request)

**Comment by varungupta85** [comment]
Dear @AlexLakatos, thanks for commenting on the issue. I didn't mean to suggest that I would complete the second part myself. I still intended to use Nexmo `verify` API to complete the second part once the user receives the code by other means and they enter it.

I have been having some problems with using the `verify` API lately. I am observing a high number of expired verifications which is severely affecting my app. I myself have experienced it many times that I don't receive the code and have to wait for the call to arrive. On closer examination I found that I may be able to trigger the call myself using the `control` API using the `trigger_next_event`. However users are not always willing to receive the OTP on call and still prefer it to receive via SMS.

I have a couple of questions.

 1. How do I resend the same code again to the user? When I try to invoke the `request` API again using the same number, I get an error back saying concurrent verifications to the same number are not allowed and the code is not sent.

 2. I guess I misunderstood the `pin_expiry` and `next_event_wait`. Could you tell me if my below understanding is correct. If I set `pin_expiry` to 300 seconds and `next_event_wait` to 30 seconds, then if I try to call the `request` API again after 30 seconds, I will not get the concurrent verification error but the user will receive the same code again by SMS.

I have tried to experiment with `pin_expiry` in the past and although the default value suggested in the documentation is 300 seconds, I don't get a new PIN for more 10-15 minutes.

**Comment by AlexLakatos** [comment]
Hi,
To answer your questions:
1. You need to first `cancel` the first request and then invoke the `request` API again. You can't have two concurrent verifications on the same number.
2.  `pin_expiry` and `next_event_wait` don't affect the ability to make another request. You can't have two concurrent requests on the same number. If you set pin_expiry to 300 seconds and next_event_wait to 30 seconds, the API will move to the next event every 30 seconds (i.e. Send SMS, retry sending SMS, make a phone call with the code in text-to-speech)

**Comment by varungupta85** [comment]
Hi @AlexLakatos, thanks for the response. I understood how to resend the code. I have a follow up question on the "next event". I was planning on adding a button in my app to get the OTP on call if they don't receive the SMS and I was planning on calling the `control` API with command `trigger_next_event`. Is this a correct approach? Or is it possible that when I trigger the next event, it may just retry to send the SMS. Although, I have never received the OTP code on SMS twice.

**Comment by AlexLakatos** [comment]
I believe that is the right approach, `trigger_next_event`

**Comment by varungupta85** [comment]
Great. Thanks @AlexLakatos. I will close the issue.
