### ISSUE TITLE
Verification code different on call than SMS

### ISSUE THREAD

**Issue by varungupta85** [Vonage/vonage-node-sdk#185]
I use the `verify` API to verify user's phone number. I am adding a control to get the verification code on call if a user has not received it on SMS. I use the `control` api to initiate a call to the user. I get the same code on the first call but if I initiate one more call, then I get a different code and the previous code is no longer valid.

Is that expected behavior?

CC @AlexLakatos

**Comment by AlexLakatos** [comment]
Yeah, that's the expected behavior if the pin expired in the meantime. You can fiddle with `pin_expiry` if you want the pin to stay the same for a longer period of time. You can take a look at the API specs if you need to [here](https://developer.nexmo.com/api/verify)
