### ISSUE TITLE
Call for verify API takes a long time 

### ISSUE THREAD

**Issue by varungupta85** [Vonage/vonage-node-sdk#186]
I am using `verify` API to verify user's phone number. Users can request the code via a call to their number if they don't receive the code via SMS within 30 seconds. I use the `control` API to trigger the call. I am observing that the call takes a long time (around 30 seconds) to arrive. Is there a way to reduce this delay?

**Comment by AlexLakatos** [comment]
Yes, you can update `next_event_wait` to be shorter than that. The docs for it are [here](https://developer.nexmo.com/api/verify)
