### ISSUE TITLE
Sales team not responding

### ISSUE THREAD

**Issue by axchanda** [Vonage/vonage-node-sdk#187]
The sales team does not respond to emails or phone calls. What to do now to purchase or to get support. I know this is not relevant to technology, but need support from the sales  IMMEDIATELY! Please support.

**Comment by AlexLakatos** [comment]
Hi,
The best way to reach support is to email support@nexmo.com. Support has a free tier, so you don't need to purchase it. If you want to reach sales, you can email sales@nexmo.com

Cheers,
Alex
