### ISSUE TITLE
TypeScript - Typings

### ISSUE THREAD

**Issue by ghost** [Vonage/vonage-node-sdk#190]
Hi,

I am currently using your NPM module in a TypeScript project.

I tried to install the typings using the following commands `npm i --save-dev @types/nexmo` and `npm i --save-dev @types/nexmo-node`. Both commands end up with a 404.

Are you planning to provide a `.d.ts` file for your NPM module?

**Comment by AlexLakatos** [comment]
Hi @jackTheRipper ,
We are not planning to support TypeScript in the near future. Could you tell us about your use case so we can consider it?

Cheers,
Alex

**Comment by ghost** [comment]
Hi @AlexLakatos,

I am currently building a micro-service to interact with your APIs. The micro-service is using your NPM module and is entirely build in TypeScript.

For now, I can compile by creating an `index.d.ts` with this single line inside `declare module 'nexmo';`.

It works but I am loosing all the advantages of working with TypeScript.

Could it be possible for you to plan an `index.d.ts` with all the signature of your modules and functions?

**Comment by ghost** [comment]
Hi @AlexLakatos , any update for that?

**Comment by AlexLakatos** [comment]
Hi @jackTheRipper,
I've considered adding TypeScript typings and won't have the time until later this year with the re-write in version 3. Let me know if you'd like to add the typings yourself and I'll try to help.

Cheers,
Alex

**Comment by ghost** [comment]
Hi @AlexLakatos, that’s ok for me. However I will push it per functionalities if it’s ok for you instead of opening a big PR which will take ages for being reviewed.

I will start with the “verify” functionality. Is it ok for you?

**Comment by AlexLakatos** [comment]
Perfect! Let me know if you need any help. If you want to chat in sort of real time, please join our community slack: https://developer.nexmo.com/community/slack

**Comment by julien-c** [comment]
Very interested in this too. Considering the (small) size of the codebase, a full rewrite to Typescript would be even better (and seems like not too big of a project).

Let me know if that is something you'd be interested in.

**Comment by ghost** [comment]
Hey, just finished the verify API for our project. I will push the .d.ts
file this week end

**Comment by ghost** [comment]
Done.

**Comment by julien-c** [comment]
Awesome @jackTheRipper

**Comment by AdelBachene** [comment]
@jackTheRipper @AlexLakatos  any Update on publishing the .d.ts ?

**Comment by ghost** [comment]
Hi @AdelBachene - I updated the PR based on the comment of @AlexLakatos - let's see if everything is alright for him

**Comment by AlexLakatos** [comment]
I think the new update makes it ok for me. Are you using the typings in a project by any chance?

**Comment by ghost** [comment]
Yes, we were using them in Adidas. Maybe @eduardostuart - @filfreire or @nekgasov can confirm we are still using it

**Comment by filfreire** [comment]
@jackTheRipper @AlexLakatos I confirm, it's still being in use, going forward with PR https://github.com/Nexmo/nexmo-node/pull/241/files would enable us to remove unnecessary code on our end 🙂

**Comment by AlexLakatos** [comment]
Thanks for confirming, I'll release in the next update!

**Comment by ghost** [comment]
Thank you @filfreire :D 

We are a good WWE combo xD

**Comment by filfreire** [comment]
@jackTheRipper only a matter of time to get the tag team championship belts 😉

**Comment by felipeplets** [comment]
@AlexLakatos do you have an expected date for the next version?

**Comment by AlexLakatos** [comment]
Tentative date is 17-21 June
