### ISSUE TITLE
Sending Korean Text not working

### ISSUE THREAD

**Issue by Cariaga** [Vonage/vonage-node-sdk#195]
app.get('/SMS/:recipient/:message', function (req, res){
  let sender= "825080825012";
  let recipient = req.params.recipient.split(",");
  let message = req.params.message;

  //console.log(message);

  for (i = 0; i < recipient.length; i++) { 
    nexmo.message.sendSms(sender, recipient[i], message,{type:'unicode'},
    (err,responseData)=>{
      if(err){
        console.log(err);
    }else{
      console.dir(responseData);
    }
  });
  }
  res.send("Sent all to " +recipient);
});

**Comment by AlexLakatos** [comment]
Hi @Cariaga ,

Can you show me the error you're getting? And maybe some sample text so I can try to reproduce your issue.

Cheers,
Alex

**Comment by Cariaga** [comment]
i'm not receiving any error but after reducing text to 70 it works.. is this a limitation?

**Comment by AlexLakatos** [comment]
There is a help article detailing the 70 characters limit for unicode: https://help.nexmo.com/hc/en-us/articles/204076866-How-long-is-a-single-SMS-body-
