### ISSUE TITLE
Promise seems to be not working

### ISSUE THREAD

**Issue by arvi** [Vonage/vonage-node-sdk#197]
Hello,

It seems the `async/await` pattern is not working. 
```js    
  const { request_id: requestId, status, error_text: errorText } = await nexmo.verify.request({
      number: `639151112233`,
      brand,
      code_length: 6,
      format: 'json',
    });
```
Only the callback pattern is working. Is this a bug or just not supported? Thanks a lot.

**Comment by mheap** [comment]
Hey @arvi,

Unfortunately only callbacks are supported at the moment. We'll be working on a promise based library later this year

**Comment by fauna5** [comment]
In the meantime you could always wrap the API using promisify (requires Node 8+)
https://nodejs.org/dist/latest-v8.x/docs/api/util.html

Here's an example using the sendSms API

```
const util = require('util');
...
const sendSms = util.promisify(
  nexmoClient.message.sendSms.bind(nexmoClient.message),
);

async function sendMessage() {
  try {
    await sendSms('bob', TO_NUMBER, 'hello');
    console.log('success!');
  } catch (error) {
    console.log('sad face');
  }
}

sendMessage();
```

**Comment by arvi** [comment]
@mheap thanks for the clarification 😄 
@fauna5 woaah! I didn't know about promisify. 😄 

What I did was to return an `ES6 promise` like this and it worked:

```js
import httpStatus from 'http-status';
import Nexmo from 'nexmo';
import config from './../config';

const { brand } = config.site;
const { apiKey, apiSecret } = config.nexmo;

const nexmo = new Nexmo({
  apiKey,
  apiSecret,
});

export const requestVerification = (mobileCountryCode, mobileNumber) =>
  new Promise((resolve, reject) => {
    nexmo.verify.request(
      {
        number: `${mobileCountryCode}${mobileNumber}`,
        brand,
        code_length: 6,
        format: 'json',
      },
      (err, result) => {
        if (err) {
          const error = new Error(err.message);
          error.code = httpStatus.INTERNAL_SERVER_ERROR;
          reject(error);
        } else {
          const { request_id: requestId, status, error_text: errorText } = result;
          if (status !== '0') {
            const error = new Error(errorText);
            error.code = httpStatus.UNAUTHORIZED;
            reject(error);
          }

          resolve({
            ok: true,
            requestId,
          });
        }
      },
    );
  });

export const verifyPin = (pin, requestId) =>
  new Promise((resolve, reject) => {
    nexmo.verify.check(
      {
        code: pin,
        request_id: requestId,
        format: 'json',
      },
      (err, result) => {
        if (err) {
          const error = new Error(err.message);
          error.code = err.code ? err.code : httpStatus.INTERNAL_SERVER_ERROR;
          reject(error);
        } else {
          if (result) {
            const { status } = result;

            if (status !== '0') {
              const error = new Error('Invalid pin. You may have entered a wrong pin or your pin expired.');
              error.code = httpStatus.BAD_REQUEST;
              reject(error);
            }

            resolve({
              ok: true,
            });
          }

          const error = new Error('Invalid pin. You may have entered a wrong pin or your pin expired.');
          error.code = httpStatus.BAD_REQUEST;
          reject(error);
        }
      },
    );
  });
```

**Comment by fauna5** [comment]
LGTM 👍

**Comment by nathalieDOXA** [comment]
> In the meantime you could always wrap the API using promisify (requires Node 8+)
> https://nodejs.org/dist/latest-v8.x/docs/api/util.html
> 
> Here's an example using the sendSms API
> 
> ```
> const util = require('util');
> ...
> const sendSms = util.promisify(
>   nexmoClient.message.sendSms.bind(nexmoClient.message),
> );
> 
> async function sendMessage() {
>   try {
>     await sendSms('bob', TO_NUMBER, 'hello');
>     console.log('success!');
>   } catch (error) {
>     console.log('sad face');
>   }
> }
> 
> sendMessage();
> ```

Hi @fauna5 , could you let me know what is the nexmoClient.message that you bind for the request?

I always get the following error when doing this approach:
`(node:614) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '_nexmo' of undefined
    at sendSms (/Users/nathalietran/Documents/dev/tmm/retail-customer-be/node_modules/nexmo/lib/Message.js:46:12)
    at Promise (internal/util.js:274:30)
    at new Promise (<anonymous>)
    at sendSms (internal/util.js:273:12)
    at sendingSms (/Users/nathalietran/Documents/dev/tmm/retail-customer-be/src/auth/test.js:17:31)
    at Object.<anonymous> (/Users/nathalietran/Documents/dev/tmm/retail-customer-be/src/auth/test.js:69:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
(node:614) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:614) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Thank you in advance.

**Comment by AlexLakatos** [comment]
@nathalieDOXA `nexmoClient` is the `Nexmo` instance. Our docs usually have this code for instantiating a client:
```
const Nexmo = require('nexmo')

const nexmo = new Nexmo({
  apiKey: NEXMO_API_KEY,
  apiSecret: NEXMO_API_SECRET
})
```

so if you instantiate it with `nexmoClient` instead, it should work for that code @fauna5 was referencing:

```
const Nexmo = require('nexmo')

const nexmoClient = new Nexmo({
  apiKey: NEXMO_API_KEY,
  apiSecret: NEXMO_API_SECRET
})
```

**Comment by soullivaneuh** [comment]
> Unfortunately only callbacks are supported at the moment. We'll be working on a promise based library later this year

Using Promise as default is quite a must have to avoid some hacks like https://github.com/Nexmo/nexmo-node/issues/197#issuecomment-409252927 (thanks @arvi BTW!).

Could we re-open the issue until this got implemented?
