### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by Regnised** [Vonage/vonage-node-sdk#201]
I send SMS and get a callback with the error

` { message: 'Server Error',
statusCode: 504,
headers: 
 { server: 'nginx',
   date: 'Tue, 11 Sep 2018 14:33:10 GMT',
   'content-type': 'text/html',
   'content-length': '176',
   connection: 'close',
   'x-frame-options': 'deny',
   'x-xss-protection': '1; mode=block;',
   'strict-transport-security': 'max-age=31536000; includeSubdomains',
   'content-disposition': 'attachment; filename="api.txt"',
   'x-nexmo-trace-id': '0ad2e1a2a9246b2de9d2802f86ba0fe5' } }`

**Comment by AlexLakatos** [comment]
There was an incident with our API, you can monitor it here: https://www.nexmostatus.com/incidents/qdl3bhsq1cbz
