### ISSUE TITLE
Media#upload Test Fails on Windows

### ISSUE THREAD

**Issue by cr0wst** [Vonage/vonage-node-sdk#213]
The following fails on Windows because there is no `/dev/null` file:

```js
// From Media-test.js
  describe("#upload", function() {
    // @TODO Add assertions for POST body
    // @TODO Add mocks for request
    it("should call the correct URL (file provided)", function() {
      return expect(this.media)
        .method("upload")
        .withParams({ file: "/dev/null" })
        .to.postFile.to.url("/v3/media");
    });
```

Since the test is only using `/dev/null` as a dummy file to test the upload functionality, it might be worthwhile to either provide a test asset, or to create and destroy a test asset before the test is run.

```
  1) Media
       #upload
         should call the correct URL (file provided):
     Uncaught Error: ENOENT: no such file or directory, open 'C:\dev\null'
```

**Comment by janowsiany** [comment]
@AlexLakatos if still valid i will work on that.

**Comment by AlexLakatos** [comment]
that's still failing @janowsiany, feel free to work on it!

**Comment by janowsiany** [comment]
What Windows and Node.js version are you testing on? I checked on Windows 10 and node 8.12.0 and it is fine.

**Comment by AlexLakatos** [comment]
@cr0wst what was your Node / Windows versions when you tested?

@janowsiany you can have a look at our upcoming Travis setup here for the targets https://github.com/Nexmo/nexmo-node/pull/216/files

**Comment by janowsiany** [comment]
@AlexLakatos just checked this and Travis says that the build is successful.
https://travis-ci.org/janowsiany/nexmo-node/builds/445877030
Am i missing something?

**Comment by cr0wst** [comment]
I think @AlexLakatos' comment might have been in reply to you asking if you could work on it, not to your proposed changes. It looks like this now tests fine with Windows and he's in the process of reviewing #221.
