### ISSUE TITLE
Is there a reason that you do not expose the module via module.exports?

### ISSUE THREAD

**Issue by passkey1510** [Vonage/vonage-node-sdk#22]
Since most of the libraries use module.exports so that we could easily import via a simple require, I don't know if there are particular reasons that you don't do that. Consequently, I have to import it by specifying the absolute path, such as:

```
var nexmo = require('../node_modules/easynexmo/lib/nexmo');
```

This is not very convenient since I have to change this each time I move the module that use nexmo.

Thanks

**Comment by passkey1510** [comment]
Oh nevermind, the right syntax to include the module was 

```
var nexmo = require('easynexmo');
```

I still think it worth mentioning in the doc :). I'm closing this issue!

**Comment by pvela** [comment]
Thanks for the suggestion. The readme is updated.
