### ISSUE TITLE
[BETA] "to" and "from" params are in different order between SMS and Messages

### ISSUE THREAD

**Issue by fauna5** [Vonage/vonage-node-sdk#233]
Send a text message

`nexmo.message.sendSms(sender, recipient, message, options, callback);`

Send a Messages API message

`function send(to, from, message, callback)`

As they are not named parameters then it's easy to get mixed up. Should we swap then? Will it cause a lot of pain for exiting users.

**Comment by fauna5** [comment]
I also note that the HTTP API lists `from` first:

```
curl -X POST https://api.nexmo.com/v0.1/messages \
  -H 'Content-Type: application/json' \
  -H 'Accept: application/json' \
  -d '{
    "from": { "type": "sms", "number": "Nexmo" },
    "to": { "type": "sms", "number": "441234567890" },
    "message": {
      "content": {
        "type": "text",
        "text": "Hello from Nexmo"
      }
    }
  }'
```

**Comment by fauna5** [comment]
@AlexLakatos any thoughts?

**Comment by AlexLakatos** [comment]
the api is not order specific, but if it make life easier for you, I can swap them in the next beta

**Comment by AlexLakatos** [comment]
it would help if I can see usage data from chart.io of the beta user agent and of this endpoint specifically

**Comment by fauna5** [comment]
There's no data in chart.io for the user agent :(

**Comment by fauna5** [comment]
It confused us twice so far, so it'd be good to swap. I'll send a PR. We will need to communicate this to existing customers. How do we do that? Should it be a major version bump too?

**Comment by mheap** [comment]
This is only in the beta channel so we can do a minor version bump

**Comment by AlexLakatos** [comment]
Talked to Hugh and got his blessing, looked at usage data and the disruption is minimal, and we can email the affected accounts directly.

**Comment by kellyjandrews** [comment]
@mheap - Based on the documentation, looks like this was never implemented - is it still an issue, or can we close this?

**Comment by mheap** [comment]
Still an issue, but is a breaking change. Push to v3

**Comment by kellyjandrews** [comment]
@mheap Wouldn't I be changing the messages beta api?

**Comment by mheap** [comment]
Yep. I'm assuming there will be a beta messages module for v3 and we could make the change there

**Comment by manchuck** [comment]
@fauna5 Version 3 of the SDK was deployed, and sending an SMS now requires an SMS Parameters object to be passed instead. You can install `@vonage/sms` or update the latest SDK to try it out. FYI that V3 of the SDK is all `async` now, so the uplift might be a lot.
