### ISSUE TITLE
Expo support

### ISSUE THREAD

**Issue by spyshower** [Vonage/vonage-node-sdk#243]
Hello,

I tried installing this package in my Expo (React Native) environment. I get this error:

> The package at "node_modules/nexmo/lib/Nexmo.js" attempted to import the Node standard library module "fs". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo

After checking it up, I found that it's not possible to use Node.js packages in Expo. Are there any plans to fix that?

Or alternatively, how am I supposed to use Nexmo?

Thank you!

**Comment by AlexLakatos** [comment]
Hi,

This isn't a client side library, it's a server side node library. As a security concern, we advise agains using the library in a client (React Native) application, but rather buid a middleware server (with express for example) that uses the nexmo library,  and then make http requests between your react native application and your middleware server using Nexmo.

What Nexmo API are you trying to use?

We do have a client side sdk that does in-app messaging, in-app calling and in-app video. https://developer.nexmo.com/client-sdk/overview

Cheers,
Alex

**Comment by spyshower** [comment]
Hey @AlexLakatos ,

I want to send a simple SMS in order to implement phone auth. I managed to do it with a simple fetch:

```
let response = await fetch("https://rest.nexmo.com/sms/json", {
      body: "from=appName&text=O κώδικος σου είναι: " + random +
        "&to=" + this.state.countryCode + this.state.phoneNumber +
        "&type=unicode" +
        "&api_key=xxx&api_secret=xxx",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded"
      },
      method: "POST"
    }) 
```
May I ask why I shouldn't do this on client?

Thanks!

**Comment by AlexLakatos** [comment]
Hi,

Because that is not secure. Anyone who manages to decompile and take a look at the client code will have your key and secret and can use them to send SMSes from the account.

Cheers,
Alex
