### ISSUE TITLE
Add proxies support

### ISSUE THREAD

**Issue by MarcDelp** [Vonage/vonage-node-sdk#245]
Hi,

I just started experimenting on Nexmo and I have an issue regarding my proxy configuration.
I'm running my Node.JS server locally with a ngrok to expose it to hooks, and I have configured my voice application to contact it when calling a given phone number.

My current pipeline is the following:
- user arrives on voice channel and gets a greating from the server;
- user then talks, what he says is recorded;
- I now want to download the file recorded.

Everything works fine until I try to download the audio file.

My code (same as in https://developer.nexmo.com/voice/voice-api/building-blocks/download-a-recording#try-it-out):
```js
nexmo.files.save(req.body.recording_url, 'test.mp3', (err, res) => {
  if(err) { console.error(err); }
  else {
    console.log(res);
  }
});
```

The error I get:

```
error: problem with API request detailed stacktrace below
error: { Error: connect ETIMEDOUT 169.63.86.162:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '169.63.86.162',
  port: 443 }
{ Error: connect ETIMEDOUT 169.63.86.162:443
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '169.63.86.162',
  port: 443 }
```

The result is the same when I replace `req.body.recording_url` with `req.body.recording_uuid`.

This seems to be related to the fact that I am behind a proxy and my configuration is ignored.
I have my CLI variable `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` set, but they are not used when using the nexmo lib. How do I have to setup these variables to enable the lib to work properly? I couldn't find any information about it so far.

Moreover, when doing the tutorials, the use of the Nexmo CLI is recommanded. Though when doing `nexmo setup ...`, I was already having connection timeout issues. I managed to avoid them by using the online interface (dashboard), but I can't do the same when it comes to coding the application.

Thanks!

**Comment by AlexLakatos** [comment]
Proxies are not currently supported in the library. That's the reason both this and the CLI are failing.

**Comment by soulchild** [comment]
I see that you're using the `request` library which has pretty solid proxy support out-of-the-box and should automatically honor the usual environment variables, like `HTTPS_PROXY`. Are there any specific reasons why this is not working, @AlexLakatos, @kellyjandrews?

EDIT: Well, it [looks like](https://github.com/Vonage/vonage-node-sdk/blob/2.x/src/HttpClient.js#L110) the library is not really using `request` to make the requests but instead uses Node's standard `https` and `http` module. Why? :smile:

**Comment by kellyjandrews** [comment]
@soulchild I've inherited this - so not exactly sure why things are the way they are.  I have a new version that will hopefully be out Q3.
