### ISSUE TITLE
Change default to https

### ISSUE THREAD

**Issue by ecwyne** [Vonage/vonage-node-sdk#25]
Per https://help.nexmo.com/hc/en-us/articles/213877768-Enforcing-mandatory-use-of-secure-HTTP-HTTPS-on-Dec-15th-2015

**Comment by damienwhaley** [comment]
I've just made a pull request for this. See https://github.com/pvela/nexmo/pull/26

**Comment by pvela** [comment]
Thanks to @damienwhaley, this issue is closed.
