### ISSUE TITLE
Using library from a Cloud hosted function

### ISSUE THREAD

**Issue by whitetigle** [Vonage/vonage-node-sdk#255]
Hi!
I'm trying to use the lib from a Node.js hosted function but since it's a limited environment, some tests are failing, especially in regard to the UserAgent which can't be written since the lib can't read the package.json file.

So I get a warning: `Could not load package details`. The user agent is set to `'User-Agent': 'nexmo-node/UNKNOWN node/UNKNOWN`

And I think that's why I get HTTP 401 error when I want to query the service from a Function while it works on my local machine.

If that's the case how can I bypass this behavior? 
Thanks!

**Comment by whitetigle** [comment]
After more testing using postman this time, it seems it's not a problem after all. I'll check elsewhere to understand where the problem comes from. Since it's a 401 then maybe it's something related to the jwt token.

**Comment by whitetigle** [comment]
I enabled debug and here's the request I get when using the lib: 
```json
{
  "host": "api.nexmo.com",
  "port": 443,
  "path": "/v1/calls",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json",
    "Accept": "application/json",
    "User-Agent": "nexmo-node/UNKNOWN node/UNKNOWN",
    "Content-Length": 154,
    "Authorization": "Bearer someJWTToken"
  }
}
```

output is `info: response ended: 401`

**Comment by whitetigle** [comment]
ok it seems I had a problem with some config parameters. So it's solved on my side.

**Comment by AlexLakatos** [comment]
Thanks for figuring it out. If you think it's a common problem, post the solution here as well please for others to find.

**Comment by whitetigle** [comment]
Hi! No real problem there. Thanks.I really messed up with the parameters.
Nonetheless, what I can do is confirm that we can use nexmo in a serverless function without any problems 😃

**Comment by whitetigle** [comment]
However my remark regarding User-Agent is still valid: it does not work in that environment. But it seems it really does not matter.

**Comment by AlexLakatos** [comment]
It really doesn't, we're using the User-Agent to segment usage, not really blocking anything. I still haven't figured out how to access the package.json in a serverless environment, so I can have consistency.
