### ISSUE TITLE
Unable to use NexmoClient in DotnetCore Web Application

### ISSUE THREAD

**Issue by Anilm19** [Vonage/vonage-node-sdk#268]
rtc_cache.js:26 Refused to create a worker from 'blob:https://ApplicationName/03e4c988-990e-49ae-a4b8-fd4d84cc6a39' because it violates the following Content Security Policy directive: "script-src * 'unsafe-inline' 'unsafe-eval'". Note that 'worker-src' was not explicitly set, so 'script-src' is used as a fallback.

 rtc_cache.js
 this.worker = new Worker(URL.createObjectURL(cache_worker.cache_worker_blob));
Failed to create new Worker

**Comment by AlexLakatos** [comment]
Hi,

This is an issue related to the nexmo-client library, not the nexmo Node.js library. And this is the repo for the Node.js server SDK. 

Could you please send an email with this problem to support@nexmo.com?

Thanks,
Alex
