### ISSUE TITLE
Typescript: message proprety does not exist on type 'Nexmo'

### ISSUE THREAD

**Issue by soullivaneuh** [Vonage/vonage-node-sdk#278]
With the following code:

```typescript
import Nexmo from 'nexmo';
const nexmo = new Nexmo({
  // @see https://github.com/Nexmo/nexmo-node/issues/277
  applicationId: '',
  apiKey: 'xxx',
  apiSecret: 'xxx',
});
nexmo.message.sendSms('test', '620919191', 'this is a test');
```

I have:

```
TS2339: Property 'message' does not exist on type 'Nexmo'
```

Because of that, the library is unusable at all.

**Comment by soullivaneuh** [comment]
Correction, it works this way:

```typescript
const Nexmo = require('nexmo');
const nexmo = new Nexmo({
  // @see https://github.com/Nexmo/nexmo-node/issues/277
  applicationId: '',
  apiKey: 'xxx',
  apiSecret: 'xxx',
});
nexmo.message.sendSms('test', '620919191', 'this is a test');
```

But now I can take benefit of strict typing. For example with this class:

```typescript
import { Service, NedbServiceOptions } from 'feathers-nedb';
import { Params } from 'express-serve-static-core';
import { Application } from '../../declarations';

const Nexmo = require('nexmo');

interface SmsData {
  _id?: string;
  to: string;
  message: string;
}

export class Sms extends Service<SmsData> {
  nexmo: Nexmo;

  constructor(options: Partial<NedbServiceOptions>, app: Application) {
    super(options);

    this.nexmo = new Nexmo({
      // @see https://github.com/Nexmo/nexmo-node/issues/277
      applicationId: '',
      apiKey: 'xxx',
      apiSecret: 'xxx',
    });
  }

  create(data: SmsData, params?: Params) {
    this.nexmo.message.sendSms('Kidways', data.to, data.message)

    return super.create(data, params);
  }
}
```

I will have the following error on the class property:

```
TSError: ⨯ Unable to compile TypeScript:
src/services/sms/sms.class.ts(14,10): error TS2749: 'Nexmo' refers to a value, but is being used as a type here.
```

I think import method should be fully supported to fix this issue.

**Comment by AlexLakatos** [comment]
The typings support is partial for now and the typings work for the Verify API currently. The SMS API is next on the list to add support for.
We also accept pull requests if you'd like to help fix this issue.

**Comment by soullivaneuh** [comment]
I'm on a really no time moment sorry. If the issue is still not resolved when I'll have more time, I'll notify you about starting a work on it. :+1:

**Comment by ecwyne** [comment]
@AlexLakatos is there any interest in converting the entire project to Typescript? The current structure would be map fairly easily, and it's much easier to keep ts docs up to date and correct that way.

I would be happy to take a look at setting it up if you let me know which branch I should use as a base

**Comment by kellyjandrews** [comment]
Wanted to drop a line here - I'm working on setting up a v3 for the Node SDK, and it will be built with TypeScript.  There will be some typings added to the current version, but we have bigger plans for v3 and will focus the effort there for a better overall experience. 

If you want to submit a pull request for v2 to help me out - more than happy to take a look and see what we can implement. Thanks!

**Comment by kellyjandrews** [comment]
Message Types were added in v2.9.1 - let me know if you have any other issues.
