### ISSUE TITLE
Need to know the proper way to implement numberInsight and the callback

### ISSUE THREAD

**Issue by taymoork2** [Vonage/vonage-node-sdk#28]
I'm currently stuck trying to implement the callback for the numberInsight API
I'm "new" to javascript and express so any help would be much appreciated
I need to use the api to extract the city data from phone number when they text in and i'm getting stuck at the callback portion :(

**Comment by leggetter** [comment]
@taymoork2 closing this as it's an old query. Sorry nobody responded to you. But please do reopen if you still have this question.
