### ISSUE TITLE
How to send to sms to specific country

### ISSUE THREAD

**Issue by bsor-dev** [Vonage/vonage-node-sdk#287]
I'm based on philippines but the client is on singapore is it automatic or do I have to config something before it works?

**Comment by AlexLakatos** [comment]
The Nexmo routing is adaptive and automatic, so you won't need to config anything location specific for SMS.

Depending on your specific use case, you might need to rent a Singapore virtual number in the [Nexmo dashboard](https://dashboard.nexmo.com/buy-numbers), and use that as the Sender ID when you send the SMS with the library, for example:

```
nexmo.message.sendSms(NEXMO_NUMBER, RECIPIENT_NUMBER, TEXT, (err, responseData) => {
    if (err) {
        console.log(err);
    } else {
        if(responseData.messages[0]['status'] === "0") {
            console.log("Message sent successfully.");
        } else {
            console.log(`Message failed with error: ${responseData.messages[0]['error-text']}`);
        }
    }
})
```

**Comment by lornajane** [comment]
I don't think we need to do anything more so I'll close this issue for now. Shout if you need anything else!
