### ISSUE TITLE
Requesting sample code showing how to stream mp3 file to websocket

### ISSUE THREAD

**Issue by Rotorsoft** [Vonage/vonage-node-sdk#288]
Hi. Do you have some code to share showing how to stream an mp3 file to the websocket? I'm trying to record the entire conversation and when the audio is streamed via the api (calls.stream...) it doesn't get picked up by the recorder nor it's streamed back through the socket (I guess that's the intended functionality). Thanks for your help!

**Comment by kellyjandrews** [comment]
I think what you would need to do here is connect another call to the websocket and stream from there. Let me know if you are still having issues.
