### ISSUE TITLE
nexmo.message.sendSms is not working on AWS lambda

### ISSUE THREAD

**Issue by zolbayars** [Vonage/vonage-node-sdk#292]
I've deployed a phone number verifier lambda function through serverless. The `nexmo.message.sendSms` is working without an issue on my local dev environment (tested it with `serverless offline`). But I don't think it's working after deployed to AWS. 

**Here's what I'm doing:** 

```
const Nexmo = require('nexmo');
const privateKey = require('./privateKey');

const getNexmoInstance = (environment) => {
  const nexmo = new Nexmo({
    apiKey: environment.nexmoAPIKey,
    apiSecret: environment.nexmoAPISecret,
    applicationId: environment.nexmoAPPId,
    privateKey: Buffer.from(privateKey.key),
  }, {
    debug: true,
  });

  return nexmo;
};

const sendSMS = async (from, to, text, environment) => {
  const nexmo = getNexmoInstance(environment);
  nexmo.message.sendSms(from, to, text, { type: 'unicode' }, (err, responseData) => {
    console.log('nexmo err', err);
    console.log('nexmo responseData', responseData);
  });
  return null;
};
```
See that log messages inside the callback? (`console.log('nexmo err', err);`, etc). They're not showing up after deployed (As I said, working fine on local). 

Since I set the `debug: true`, it's logging the following: 
- `info: sending message from +44750....` 
- `info: Request: { host: 'rest.nexmo.com', port: 443....` 

But the callback is not getting called, no message log is registered on the Nexmo dashboard too. Is there any additional serverless related config that I'm unaware of? 

- Nexmo package version: `2.6.0`
- Runtime: `nodejs12.x`

**Comment by zolbayars** [comment]
Update: 
I tried with an internal API and it's working fine. 
```
nexmo.options.rest.postUseQueryString(
    "/sms/json",
    {"from": "Demo", "to": "447700900000", "text": "Testing"},
    function(err, data){
        console.log(err);
        console.log(data);
    },
    false // Don't use JWT, fall back to API key/secret
);
```

But it says: 

> This section uses internal APIs and should not be relied on. We make no guarantees that the interface is stable. Relying on these methods is not recommended for production applications

What shall I do?

**Comment by AlexLakatos** [comment]
The first code you posted has a `return null` and I think that means the Lambda finishes execution before the callback returns, and the callback code is never running.  What happens if you remove the `return null` from there, and put it inside the callback?

**Comment by kellyjandrews** [comment]
@zolbayars were you able to get through this issue?
