### ISSUE TITLE
Replace deprecated "request"

### ISSUE THREAD

**Issue by TrySound** [Vonage/vonage-node-sdk#294]
"request" package is deprecated.

https://github.com/request/request#deprecated

A few possible alternatives
- https://github.com/node-fetch/node-fetch
- https://github.com/axios/axios
- https://github.com/sindresorhus/got

**Comment by AlexLakatos** [comment]
Thanks for the issue, we're already looking at alternatives to replace request.

**Comment by rafaeelaudibert** [comment]
As part of Hacktoberfest, could I potentially replace the usage of request with something suggested by @TrySound? I personally like Axios and think it would be a good fit for the project.

**Comment by OmkarPh** [comment]
Hi @AlexLakatos can I work on this?
I prefer fetch though

**Comment by mheap** [comment]
This issue is outdated due to work on a new version of this SDK. Thanks for your interest!

**Comment by lawrenceong** [comment]
@mheap Is there another SDK other than this?  Looks like this SDK is still using the requests library.
