### ISSUE TITLE
Nexmo constructor changes of given options object

### ISSUE THREAD

**Issue by Snelius30** [Vonage/vonage-node-sdk#295]
Here https://github.com/Nexmo/nexmo-node/blob/master/src/index.js#L103
must be copy of an options object instead of direct usage.

**Comment by AlexLakatos** [comment]
Can you explain why it must be a copy, please?

**Comment by Snelius30** [comment]
Cuz it's changing passed object. Otherwise i need to make a copy to pass the options object which wrong, no one libs should change passed args without return needs.

**Comment by AlexLakatos** [comment]
That is not changing the options object though. It's changing some other class properties, that aren't passed in.

**Comment by Snelius30** [comment]
I can wrong with code line. Just check this out
```
const Nexmo = require('nexmo');
const options = {};
const nexmo = new Nexmo({ apiKey: 'testKey', apiSecret: 'testSecret' }, options);
console.log(options);
```
The options object will changed with internal data.

**Comment by AlexLakatos** [comment]
OK. Found the culprit: https://github.com/Nexmo/nexmo-node/blob/master/src/Nexmo.js#L40
Changing that to `this.options = Object.assign({}, options);` should do the trick. I'll get on it.
