### ISSUE TITLE
Delete all the messages from a conversation

### ISSUE THREAD

**Issue by kapil-adroitminds** [Vonage/vonage-node-sdk#301]
Hi, 
I am using conversation API and is it possible to clear all the messages from a conversation in a single call. 

Ideally I should be able to provide a conversationId and an event type = 'text' to delete all the messages in a conversation. Is it possible with current API?

**Comment by kellyjandrews** [comment]
You can delete an entire conversation, but not the messages. You would need to filter messages as a soft delete.
