### ISSUE TITLE
The API response could not be parsed.

### ISSUE THREAD

**Issue by gautiermorel** [Vonage/vonage-node-sdk#308]
Hello,

I recently got this error:

`{
Jul 13 13:10:24 babysit-eu-api app/web.4   status: 403,
Jul 13 13:10:24 babysit-eu-api app/web.4   message: 'The API response could not be parsed.',
Jul 13 13:10:24 babysit-eu-api app/web.4   body: '<!DOCTYPE html>\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     ' <html class="no-js" lang="en-US"> \n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<head>\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<title>Attention Required! | Cloudflare</title>\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<meta name="captcha-bypass" id="captcha-bypass" />\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<meta charset="UTF-8" />\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" />\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<meta name="robots" content="noindex, nofollow" />\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<meta name="viewport" content="width=device-width,initial-scale=1" />\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/cf.errors.css" type="text/css" media="screen,projection" />\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     `<!--[if lt IE 9]><link rel="stylesheet" id='cf_styles-ie-css' href="/cdn-cgi/styles/cf.errors.ie.css" type="text/css" media="screen,projection" /><![endif]-->\n` +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<style type="text/css">body{margin:0;padding:0}</style>\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<script type="text/javascript" src="/cdn-cgi/scripts/zepto.min.js"></script>\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '<script type="text/javascript" src="/cdn-cgi/scripts/cf.common.js"></script>\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +
Jul 13 13:10:24 babysit-eu-api app/web.4     '\n' +`

I am a bit confused cause it says that i should resolve a captcha, but i use the Nexmo API.

Should I be worry about that or it was just something unexpected from Nexmo ?

**Comment by dragonmantank** [comment]
This looks like the IP address of either the server you are using or your computer (if doing local development) was flagged by Cloudflare, which we have as part of our stack for spam/bot/attack prevention.

Were you running this code from a local instance or is this running on a server? If it is a server, you may want to contact your host as, especially if this is a shared server, someone may be using the server for abusive purposes (not necessarily your account, but someone else on the server). If it's your local computer, try going to `https://api.nexmo.com` and see if you get the captcha page. If you do, you can try filling out the captcha but this implies that your IP has been flagged by Cloudflare. Some more info on Cloudflare and their blocking can be found here: https://community.cloudflare.com/t/cloudflare-is-blocking-me-from-accessing-sites/12471 .

If you're still having a problem, feel free to re-open this ticket.
