### ISSUE TITLE
Error nexmo_1.default is not a constructor on typescript

### ISSUE THREAD

**Issue by Redouane64** [Vonage/vonage-node-sdk#313]
Hello!

I am using this library in NestJS project with typescript. here is example:

```ts
import Nexmo from 'nexmo';

const nexmo = new Nexmo({
    apiKey: "...",
    secretKey: "..."
})
```
When i run the app, this error occur:
```
[Nest] 228616   - 08/06/2020, 12:38:42 PM   [ExceptionHandler] nexmo_1.default is not a constructor +1ms
TypeError: nexmo_1.default is not a constructor
    at new NotificationsService (/home/redouane/Projects/notification-api/dist/notifications/notifications.service.js:31:22)
```

Any ideas on how to solve this issue? i am still quite new to Typescript and JS

**Comment by kellyjandrews** [comment]
Thanks @Redouane64 for this - I'm looking into this issue on my end as well, and should hopefully have a solution tomorrow or early next week. I'll get back with you as soon as I can.

**Comment by kellyjandrews** [comment]
Hey @Redouane64 - looks like you may be able to add the following to your code to prevent the constructor issue - 

```
/// <reference path="../node_modules/nexmo/typings/index.d.ts" />
import Nexmo from 'nexmo';

const nexmo = new Nexmo({
  apiKey: '',
  apiSecret: '',
});
```

Let me know if this helps you out any. The library has some types added, but we are still working on getting a plan for updates to the type definitions.
