### ISSUE TITLE
TypeError: Nexmo is not a constructor

### ISSUE THREAD

**Issue by tapz** [Vonage/vonage-node-sdk#317]
Upgraded from 2.8.0 to 2.9.0 and now getting this error:

```
(node:45) UnhandledPromiseRejectionWarning: TypeError: Nexmo is not a constructor
    at Object.<anonymous> (/app/services/myService.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/routes.js:4:21)
```

```
const Nexmo = require('nexmo');

const nexmo = new Nexmo({
  apiKey: config.nexmo.apiKey, 
  apiSecret: config.nexmo.apiSecret
}, {
  debug: false,
  timeout: 60 * 1000
});
```

**Comment by kellyjandrews** [comment]
Thanks - I'll take a look.

**Comment by kellyjandrews** [comment]
@tapz I guess I'm not really sure why this happens - the code for the constructor hasn't changed, and I have it working locally as well. 

I've run into this error before, and added

`/// <reference path="../node_modules/nexmo/typings/index.d.ts" />`

to get it to reference the type file - but I'm not exactly sure why it lost the reference in the first place.  As soon as I can find the culprit, I'll get a fix in so the change isn't breaking, as I don't see where it would be breaking it.

**Comment by tapz** [comment]
Thanks. I downgraded back to 2.8.0 and don't see the error anymore.

**Comment by kellyjandrews** [comment]
Thanks - I can't seem to reproduce locally now - trying to get that to happen so I can figure it out.

**Comment by kellyjandrews** [comment]
We have a fix for this coming shortly https://github.com/Nexmo/nexmo-node/pull/318

Thanks @mheap!

**Comment by kellyjandrews** [comment]
v2.9.1 should have the issue resolved - let me know if you see anything else.
