### ISSUE TITLE
Typescript typigns not working

### ISSUE THREAD

**Issue by Sorunome** [Vonage/vonage-node-sdk#354]
## Expected Behavior
You should be able to import the module with typescript: `import Vonage from "@vonage/server-sdk";`

## Current Behavior
There are multiple issues not allowing it to import correctly:
1. The module name in `typings/index.d.ts` is wrong: It is currently `vonage`, but needs to be `@vonage/server-sdk` to read `declare module '@vonage/server-sdk' { ... }`
2. `VonageApiError` is not defined, which appears in `export interface VerifyError extends VonageApiError`. Renaming `NexmoApiError` to `VonageApiError` fixes this
3. When finally importing and trying to create a new instance, it does not work:
```
import Vonage from "@vonage/server-sdk";
const vonage = new Vonage({ ... });
```
gives
```
TypeError: server_sdk_1.default is not a constructor
    at new Message (/home/sorunome/repos/famedly/contact-finder/build/src/message.js:46:23)
    at /home/sorunome/repos/famedly/contact-finder/build/src/index.js:123:25
    at Generator.next (<anonymous>)
    at fulfilled (/home/sorunome/repos/famedly/contact-finder/build/src/index.js:21:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

A possible solution for this is to
```
import * as Vonage from "@vonage/server-sdk";
const vonage = new Vonage({ ... });
```
But then you aren't able to use the `Vonage` type, which makes typings kinda useless
(still thinking of a possible solution for this one, will edit in if found)

## Possible Solution
See above

## Steps to Reproduce (for bugs)
Try to use library with typescript

## Your Environment

* SDK Version: 2.10.1
* Node Version: (e.g. Node 10.18): 14.9.0
* Operating System and version: Archlinux

**Comment by kellyjandrews** [comment]
Thanks - I'll get a new version pushed out soon as possible.
