### ISSUE TITLE
Number Types

### ISSUE THREAD

**Issue by kellyjandrews** [Vonage/vonage-node-sdk#363]
Create Typings for Number API

**Comment by 3scava1i3r** [comment]
can you please elaborate on the same

**Comment by damn-dvlpr** [comment]
Just came here to say Hi to @3scava1i3r

**Comment by kellyjandrews** [comment]
Hey @3scava1i3r - we have a Number API in the repo that would need types created for it.  

The functionality is here - https://github.com/Vonage/vonage-node-sdk/blob/master/src/Number.js
Documentation is here - https://developer.nexmo.com/api/numbers
Types file is here - https://github.com/Vonage/vonage-node-sdk/tree/master/typings

Let me know if you have any other questions. Thanks!

**Comment by privateOmega** [comment]
@kellyjandrews I tried my hands at this issue, raising a PR.

**Comment by kellyjandrews** [comment]
Thanks @privateOmega - I'll be reviewing this soon.
