### ISSUE TITLE
sendTextMessage is not working

### ISSUE THREAD

**Issue by lutfor3737** [Vonage/vonage-node-sdk#37]
I am implementing this in my hapi application. sendMessage is working fine, but sendTextMessage is not working.
var nexmo = require('easynexmo');
nexmo.initialize('KEY', 'SECRET');
function consolelog (err,messageResponse) {
if (err) {
            console.log(err);
    } else {
            console.log(messageResponse);
    }
}
nexmo.sendTextMessage(XXXXXXXXXXX,YYYYYYYYYY,'Test Meessage',consolelog); // This is not working

nexmo.sendMessage({from:XXXXXXXXXXX,to: YYYYYYYYYY, text:'Test Message'}, consolelog); // This is working fine

**Comment by pvela** [comment]
There is a 4th parameter in sendTextMessage method to send any additional options to the API. I made this parameter optional in the new version published today, please give this a try in the new version and let me know how it goes.

Thanks for raising this issue and helping in improving the library.

**Comment by lutfor3737** [comment]
It's working perfectly. Thanks for quick fix.
