### ISSUE TITLE
Allow for Full URL Overrides in Constructor

### ISSUE THREAD

**Issue by kellyjandrews** [Vonage/vonage-node-sdk#377]
## Expected Behavior
We want to allow for a full url or domain to be used in a `apiHost` or `restHost` option.

```
const vonage = new Vonage({
  apiKey: VONAGE_API_KEY,
  apiSecret: VONAGE_API_SECRET
  apiHost:'myurl.com'
})
```
```
const vonage = new Vonage({
  apiKey: VONAGE_API_KEY,
  apiSecret: VONAGE_API_SECRET
 apiHost:'https://myurl.com'
})
```

## Current Behavior
Currently the NodeJS library allows the user to override just the domain portion of the URL and the SDK throws an ENOTFOUND error:

```
// currently this does not work.
const vonage = new Vonage({
  apiKey: VONAGE_API_KEY,
  apiSecret: VONAGE_API_SECRET
 apiHost:'https://myurl.com'
})
```

## Possible Solution

There are two parts to this issue - 1) the options parsing, 2) How API's are called from the HttpClient

1. Options Parsing
This section needs to allow for both versions of a domain, fully qualified or host only. Protocol-less hosts should default to `https://`. 
https://github.com/Vonage/vonage-node-sdk/blob/master/src/Vonage.js#L74-L88

2) HTTP Client
This should remove the string concatenation in favor of storing the fully qualified domain name. 
https://github.com/Vonage/vonage-node-sdk/blob/master/src/HttpClient.js#L357-L367

**Comment by i-am-jeetu** [comment]
Hi @kellyjandrews, I want to work on this. This will be my first contribution to Vonage. Can you please assign this to me.

**Comment by Raj-Datta-Manohar** [comment]
Hi, can I work on this?

**Comment by kellyjandrews** [comment]
@Raj-Datta-Manohar There is already a pull request. Thanks for the offer!
