### ISSUE TITLE
From v1.0 update package to be `nexmo` in NPM

### ISSUE THREAD

**Issue by leggetter** [Vonage/vonage-node-sdk#39]
Nexmo now has access to the `nexmo` package.

Suggested plan:
- Mark `easynexmo` as deprecated https://docs.npmjs.com/cli/deprecate
- Publish v1.0 of this repo as `nexmo`

Any concerns or thoughts regarding this approach?

**Comment by pvela** [comment]
This sounds like a good plan. I dont see any concerns with this approach.

**Comment by leggetter** [comment]
@pvela are you happy to mark `easynexmo` as deprecated?

**Comment by pvela** [comment]
Yes I am ok with deprecating easynexmo.

**Comment by leggetter** [comment]
Thanks @pvela. You're the only collaborator on the project in NPM so please do mark it as deprecated when you get a chance.

I think the command would be:

```
npm deprecate easynexmo@0.8.5 "easynexmo is no longer maintained. Please use the `nexmo` package."
```

Update the message as you see fit 😄

**Comment by pvela** [comment]
done.

**Comment by leggetter** [comment]
Thanks @pvela 👍
