### ISSUE TITLE
Better way to catch authentication errors?

### ISSUE THREAD

**Issue by cbetta** [Vonage/vonage-node-sdk#40]
Is there a better way to catch authentication errors? At the moment if I run `nexmo.initialize(...)` with incorrect credentials the callback for a method does NOT return an `error` object. Instead the `response` object looks as follows:

```
{ 'error-code': '401',
  'error-code-label': 'authentication failed' }
```

There's a few things that would be useful here.
1. Catch authentication errors and actually return an error object instead of a response in an API call.
2. Provide a way to validate `nexmo.initialize(...)` without making an API call

**Comment by leggetter** [comment]
Thanks for this @cbetta.

@tjlytle is working on a library spec to make libraries work consistently. There are also something the libraries should do to work around some API behaviours such as this.

The spec can be found here:
https://github.com/Nexmo/client-library-specification

I think [the Errors section](https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#errors) addresses point 1.

It could be that [Creating a Client](https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#creating-a-client) could be updated to also validate credentials. @tjlytle?

**Comment by tjlytle** [comment]
I would not check credentials on construction, as that would required an API call, and it's:
- Expensive (in terms of time)
- Unexpected (if I start getting auth errors, and I've now even making a request, I'm confused).

That said, the root of this is the API returning a `200` status for something that's certainly not `ok`. The spec doesn't address the specifics of this, but libraries should unify the behaviour, and return error objects (or whatever the language does, exceptions, etc) based on either the status (new APIs) or the status of the body (legacy APIs).

For just checking credentials, could do a `nexmo.checkCredentials()` that just hits the balance API and returns a `bool` based on the success of the call.

**Comment by cbetta** [comment]
Agreed with @tjlytle about it not running by default, that's definitely not the intended behaviour.

**Comment by tjlytle** [comment]
Spec on [errors specifically](https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#errors), and [PR that addresses some of the underlying issue](https://github.com/Nexmo/client-library-specification/pull/7).

**Comment by leggetter** [comment]
I meant check that the credentials have been supplied - not that they existing within the Nexmo platform e.g. check for empty strings, null/undefined values and so on.

**Comment by tjlytle** [comment]
Definitly, from the spec:

> [Must require an authentication method (credentials or oauth) for construction.](https://github.com/Nexmo/client-library-specification/blob/master/SPECIFICATION.md#creating-a-client)

**Comment by cbetta** [comment]
Irrelevant due to many changes since this was opened.
