### ISSUE TITLE
Batch SMS'es

### ISSUE THREAD

**Issue by larssn** [Vonage/vonage-node-sdk#416]
Not a bug, more like a feature request.

So the API pretty clearly states that only one SMS can be sent per request, and that you can only do 30 requests per second.
[This](https://help.nexmo.com/hc/en-us/articles/205065817-How-to-Send-Multiple-SMS-in-a-Single-API-Request) article regarding multiple SMS'es, suggests using keep-alive connections to minimize HTTP handshakes.

Now I'm pretty sure that's not supported by this SDK, so I'm looking for options on how to handle such a scenario.
It would be nice if the SDK was transparent enough to do this behind the scenes! 🙂

**Comment by kellyjandrews** [comment]
I'm currently working on a v3 that will change much of the SDK - and this is definitely a use case I'm planning to cover. 

Unfortunately, the current SDK doesn't allow for additional headers to be passed in as options through the `sendSMS` method. It may be possible to use the `HTTPClient` directly, but it's less than ideal.

**Comment by manchuck** [comment]
Closing this issue. V3 uses `node-fetch` which optimizes the HTTP request
