### ISSUE TITLE
typings index.d.ts failing transpilation, needs an ts-ignore bypass.

### ISSUE THREAD

**Issue by diekotto** [Vonage/vonage-node-sdk#429]
Using @vonage/server-sdk with typescript doesn't transpile without an unrecommended bypass, but then it doesn't work at all.

## Expected Behavior
The expected behavior is to use the package without ts notations

## Current Behavior
The current behavior is the next.
```typescript
import * as Vonage from '@vonage/server-sdk';
const nexmo = new Vonage({
      apiKey: 'asdf',
      apiSecret: 'asdf',
    });
// throws:
// TS2351: This expression is not constructable.
// Type 'typeof import("@vonage/server-sdk")' has no construct signatures
```
  
```typescript
import Vonage from '@vonage/server-sdk';
const nexmo = new Vonage({
      apiKey: 'asdf',
      apiSecret: 'asdf',
    });
// ide don't complain, but when executing the bundle it throws a fatal error:
// TypeError: server_sdk_1.default is not a constructor
```

## Context
Now it needs to be used with this ts notations:
```typescript
import * as Vonage from '@vonage/server-sdk';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
const nexmo = new Vonage({
      apiKey: 'asdf',
      apiSecret: 'asdf',
    });
const from = 'Vonage APIs';
const to = '...';
const text = 'Hello from Vonage SMS API';

nexmo.message.sendSms(from, to, text, {}, (err, data) => {
   console.log(err);
   console.log(data);
});
// sms received
```

## Your Environment
* SDK Version:  "2.10.4"
* Node Version: v14.15.1
* TSC Version: 4.0.3
* Operating System and version: Ubuntu 20.04.1 LTS

**Comment by diekotto** [comment]
I'm editing the main post, it works with ts notations. Nulling the opts, even when documented as optional, throws fatal error. But works with an empty object.

**FROM:**
```typescript
nexmo.message.sendSms(from, to, text, null, (err, data) => {
  console.log(err);
  console.log(data);
});
```
**TO:**
```typescript
nexmo.message.sendSms(from, to, text, {}, (err, data) => {
  console.log(err);
  console.log(data);
});
```

**Comment by kellyjandrews** [comment]
@DiegoMGar would you be able to share your `.tsconfig` with me? I'd like to better understand the problem on my end.  Thanks!

**Comment by visioncored** [comment]
@kellyjandrews I also encountered this issue when I was trying out the SMS API in Firebase Cloud Functions. Here is the .tsconfig from my end.

```
{
  "compilerOptions": {
    "module": "commonjs",
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "lib",
    "sourceMap": true,
    "strict": true,
    "target": "es2017"
  },
  "compileOnSave": true,
  "include": [
    "src"
  ]
}
```

**Comment by kellyjandrews** [comment]
I have a PR coming in shortly that should fix this after release.

**Comment by kellyjandrews** [comment]
@visioncored - you may also need to add the following config:

```
        "esModuleInterop": true,
        "moduleResolution": "node",
```

I just about have things fixed up.

**Comment by ChBernat** [comment]
@kellyjandrews enums should never be included in *.d.ts files.
Typescript does not transpile *.d.ts files.

Any enum inside the *.d.ts will be ultimately unresolvable for Javascript and it won't be bundled in the final build. 

The fast/dirty workaround for this is to make enums const, but that has some drawbacks on its own.
