### ISSUE TITLE
Support for sending options to getNumbers and searchNumbers API

### ISSUE THREAD

**Issue by pvela** [Vonage/vonage-node-sdk#47]

**Comment by cbetta** [comment]
Related to #41

**Comment by pvela** [comment]
This is implemented in the latest version 0.8.0 published to npm.
Example : 
nexmo.searchNumbers('US',consolelog);
nexmo.searchNumbers('US',{pattern:3049,index:1,size:2,features:'VOICE',search_pattern:2},consolelog);
nexmo.getNumbers(consolelog);
nexmo.getNumbers({pattern:714,index:1,search_pattern:2},consolelog);
