### ISSUE TITLE
Unexpected `console.log` when sending message

### ISSUE THREAD

**Issue by mheap** [Vonage/vonage-node-sdk#496]
## Expected Behavior
No output logged to console

## Current Behavior
Output logged, including my authentication credentials

## Possible Solution
Remove https://github.com/Vonage/vonage-node-sdk/blob/2.x/src/Message.js#L73-L78

## Steps to Reproduce (for bugs)
Send an SMS with `vonage.message.sendSms`

## Your Environment
* SDK Version: 2.10.8
* Node Version: (e.g. Node 10.18): 16

**Comment by kellyjandrews** [comment]
Thanks - I'll get this removed.
