### ISSUE TITLE
Unable to resolve path to module '@vonage/server-sdk'  import/no-unresolv version 2.10.9

### ISSUE THREAD

**Issue by bbmouka** [Vonage/vonage-node-sdk#534]
`@vonage/server-sdk`  import/no-unresolv 

with  `"eslint-plugin-import": "^2.22.1"`

> error    Unable to resolve path to module '@vonage/server-sdk'  import/no-unresolved

The solution is to update package in your package.json "@vonage/server-sdk": "^2.10.8" with "@vonage/server-sdk": "2.10.8",

_=>delete  `^`_

**Comment by kellyjandrews** [comment]
This should be resolved in 2.10.10
