### ISSUE TITLE
2.10.9 missing /lib folder

### ISSUE THREAD

**Issue by amdcavallaro** [Vonage/vonage-node-sdk#535]
`2.10.9` missing `/lib` folder.

## Expected Behavior
`node_modules/@vonage/server-sdk` should have `/lib` folder.

## Current Behavior
`node_modules/@vonage/server-sdk` is missing a `/lib` folder.

## Possible Solution
Copy the existing `/lib` folder from version `2.10.8` to `2.10.9`.

## Steps to Reproduce (for bugs)
1.npm install @vonage/server-sdk
2.You'll get an error `"Error: Cannot find module '/node_modules/@vonage/server-sdk/lib/Vonage'. Please verify that the package.json has a valid "main" entry`.

For it to work I had actually copy the `@vonage/server-sdk/lib` folder from a project with `2.10.8`.

## Your Environment

* SDK Version: 2.10.9.
* Node Version: (e.g. Node 10.18): v14.17.0.
* Operating System and version: macOS Big Sur 11.4.

**Comment by dragonmantank** [comment]
Thanks for alerting about this. 2.10.10 should be valid. For some reason when 2.10.9 was published, the compile step did not run or ran into an error, yet the package was still pushed out. 

I'll leave this open for a bit in case anything else pops up, but try jumping to 2.10.10 and see if that works.
