### ISSUE TITLE
Implement promise styled api?

### ISSUE THREAD

**Issue by ulion** [Vonage/vonage-node-sdk#56]
Consider implement promise styled api?

**Comment by rlancer** [comment]
I would suggest if there is no callback to return a promise

**Comment by leggetter** [comment]
@AlexLakatos - Do you have any thoughts on a recommended approach. Do we simply recommend using `someLibrary.promisify` or is there a way of us easily adding Promise support to the library?

**Comment by shide1989** [comment]
There's a library called bluebird, which seems to be widespread and maintained (that I personally always use), i would recommend using it : https://github.com/petkaantonov/bluebird
the api documentation is available here : http://bluebirdjs.com/docs/api-reference.html
finally, adding promises nearly always consists of : 
```
const Promise = require('bluebird');

function myPromiseCall(param) {
  return new Promise(resolve, reject) {
    someAsyncCall(param, function(err, result){
      if(err){
        if(callback) callback(err);
        return reject(err);
      }
      if(callback) callback(null, result);
      resolve(result);
    });
  };
}
```
adding this support at your top level functions (like request calls) simplifies the whole callback/result management inside the api. once you start using them, you get out of all the callback hell

**Comment by AlexLakatos** [comment]
@leggetter to support both, I only know of `nodeify`, and that's not the easy way.  I would suggest people use bluebird's `Promise.promisifyAll` on importing the module, that should do the trick.

**Comment by shide1989** [comment]
@AlexLakatos it could be a good solution, but would require exhaustive testing though

**Comment by machinshin** [comment]
any update on this?

**Comment by AlexLakatos** [comment]
There are no plans to add promise support in the near future. `bluebird` worked well for me over these last few weeks though. @machinshin I would suggest you give that a try.

**Comment by bidah** [comment]
I solved it this way:

first I made this function wrapper around `nexmo.verify.request` 
```
  verifyRequest(number, callback) {
    nexmo.verify.request(
      {
        number,
        brand: "Haip"
      },
      callback
    );
  }
```

Then you can wrap the function in a function that returns a promise like so:
```
function verifyRequestPromise(phone) {
  return new Promise(function(resolve, reject) {
    verifyRequest(
      phone,
      (err, result) => (Boolean(err) ? reject(err) : resolve(result))
    );
  });
}
```

**Comment by fauna5** [comment]
Also with `util.promisify` in Node 8+ 
Docs -> https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_promisify_original

```
const util = require('util');

const verifyRequestPromise = util.promisify(nexmo.verify.request.bind(nexmo.verify));

const result = await verifyRequestPromise({
  number,
  brand: "Haip"
})
```

**Comment by julien-c** [comment]
Also +1 for native Promise support in this library. It's 2019 guys! Everyone uses Promises now.

**Comment by AlexLakatos** [comment]
I'm going to do a re-write this year, and promises are on my list of features to add with the rewrite.

**Comment by kellyjandrews** [comment]
Merge with #294
