### ISSUE TITLE
following SMS tutorial inbound messages do not appear on message logs, and don't activate callback

### ISSUE THREAD

**Issue by gocandra** [Vonage/vonage-node-sdk#575]
```
const app = require('express')()
const bodyParser = require('body-parser')

app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app
  .route('/webhooks/inbound-sms')
  .get(handleInboundSms)
  .post(handleInboundSms)

function handleInboundSms(request, response) {
  const params = Object.assign(request.query, request.body)
  console.log(params)
  response.status(204).send()
}

app.listen(process.env.PORT || 3000)
```

basically i'm sending an sms to  my phone, and when I answer the webhook is not activated.
i've set up the webhook in my number
i've setup the webhook on my application

**Comment by kellyjandrews** [comment]
I'll take a look at this and see what is wrong - doesn't look wrong to me so far - but I may be missing something.

**Comment by kellyjandrews** [comment]
@gocandra - are the webhooks publicly accessible? And is the global webhook type set to `get`?  Other than that, I'm not sure - hope you got things working.
