### ISSUE TITLE
callback is undefined in _checkToAndFrom(data).

### ISSUE THREAD

**Issue by lf94** [Vonage/vonage-node-sdk#595]
https://github.com/Vonage/vonage-node-sdk/blob/e1bb7fc6f7b7c0f6f3d5ab6e1dc57301c5d6325f/src/Message.js#L45

`callback` is undefined here.

**Comment by kellyjandrews** [comment]
Fixed here https://github.com/Vonage/vonage-node-sdk/commit/9df58ca9dd8ceccde7a6bbf85bc6db8eef197e61
