### ISSUE TITLE
can't install the package with yarn or npm 

### ISSUE THREAD

**Issue by FatmaMahmoud698** [Vonage/vonage-node-sdk#632]
I tried to install the package on nodejs project with 
`yarn add @vonage/server-sdk`
and 
`yarn add https://github.com/Vonage/vonage-node-sdk`
but no folder created on node_modules for the package 
I got this message in installation  
![1](https://user-images.githubusercontent.com/75572871/158423126-34a04386-6e23-419a-a230-1c3a8ff1efbb.PNG)

![1](https://user-images.githubusercontent.com/75572871/158424148-4666c7c1-3328-4f79-ab41-1dcdab2f4500.PNG)

node version: v16.14.0
yarn version: 1.22.17

**Comment by kellyjandrews** [comment]
Looks like something has become incompatible with the environment - I will try to investigate and see what the package is and try to get it updated for you.

**Comment by manchuck** [comment]
@FatmaMahmoud698 Can you confirm if you are still having this issue? It looks like the dependant module has been updated to support your system
