### ISSUE TITLE
RequestResponseStatusCode enum is wrong in types

### ISSUE THREAD

**Issue by eljass** [Vonage/vonage-node-sdk#649]
## Expected Behavior

We are expecting the enums [here](RequestResponseStatusCode) to match status codes on https://api.support.vonage.com/hc/en-us/articles/360025561931-What-do-the-Verify-API-response-codes-mean-

## Current Behavior

Currently the status codes are wrong in:
```js
export enum RequestResponseStatusCode {
    Success = "0",
    Throttled = "1",
    MissingParameters = "2",
    InvalidCredentials = "3",
    InternalError = "4",
    NotProcessed = "5",
    BlackListedNumber = "6",
    BlockedAccount = "7",
    QuotaExceeded = "8",
    ConcurrentVerificationNumber = "9",
    TargetNetworkNotSupported = "10",
    WrongVerificationCode = "11",
    TooManyRequests = "12",
    NoMoreEvents = "13",
    NoRequestFound = "14",
}
```

## Possible Solution

Update the typings:
```js
export enum RequestResponseStatusCode {
    Success = "0",
    Throttled = "1",
    MissingParameters = "2",
    InvalidParameters = "3",
    InvalidCredentials = "4",
    InternalError = "5",
    NotProcessed = "6",
    BlackListedNumber = "7",
    BlockedAccount = "8",
    QuotaExceeded = "9",
    ConcurrentVerificationNumber = "10",
    TargetNetworkNotSupported = "15",
    WrongVerificationCode = "16",
    TooManyRequests = "17",
    TooManyRequestIds = "18",
    NoMoreEvents = "19",
    NoRequestFound = "101"
}
```

To make this even better, these enums could be exported in a .ts file so we don't have to create our own representation of these when we are trying to access them in runtime.

## Context

We map error notifications for customers based on these status codes. Therefore it is better that they are up to date.

## Your Environment

* SDK Version: 2.10.11

**Comment by manchuck** [comment]
@eljass V3 of the SDK should now have the correct types. Can you please check if you're still having an issue?
