### ISSUE TITLE
Add active linting to tests

### ISSUE THREAD

**Issue by cbetta** [Vonage/vonage-node-sdk#67]
We should add linting to our tests and ensure all linting passes before code is merged. This will initially require one big refactor to lint all the current code. Things we should look at fixing:
- Strip trailing white space
- Pick tabs or spaces - probably 4 spaces
- Pick whether to enforce trailing semi colons
- Enforce camel case over snake case

**Comment by leggetter** [comment]
Fixed in #99 and in #107.
