### ISSUE TITLE
Make sure that URL Overrides strip ending `/` from URLs

### ISSUE THREAD

**Issue by dragonmantank** [Vonage/vonage-node-sdk#739]
## Expected Behavior

According to https://developer.vonage.com/messages/code-snippets/whatsapp/send-text, you can set the base URL for the API to `https://api.nexmo.com/`, with a trailing slash. This breaks the routing as the SDK expects the URL without a `/` at the end.

## Current Behavior

We should allow the user to enter a URL with or without a slash, and strip it if it exists.

## Possible Solution

We should be able to add some code to `server-client` in the constructor to clean this up, as well as in the main `server-sdk` package. It would need to be done in both places as `server-client` handles it for all the sub-packages, but the main package doesn't extend from there so it also needs to handle it.

## Steps to Reproduce (for bugs)

1. Create a new `Vonage` object and set the base URL to `https://api.nexmo.com/`
1. Try and hit a resource using that URL like applications

## Context

Submitted by a user in our internal devrel chat

## Your Environment

* SDK Version: 3.x
* Node Version: (e.g. Node 10.18): N/A
* Operating System and version: N/A

**Comment by manchuck** [comment]
I have checked and `vetch` will not append extra `/`
