### ISSUE TITLE
Not able to install Vonage/server-sdk

### ISSUE THREAD

**Issue by mRahulRoy** [Vonage/vonage-node-sdk#799]
## ExpectedBehaviour
It should Intsall the dependency after hitting npm install @vonage/server-sdk 

## Current Behaviour
Its saying this -  npm ERR! 404 Not Found - GET https://registry.npmjs.org/@vonage%2faudit - Not found

## Possible Solution
maintainers should check for Possible error , and should also crosscheck npm registry

## Your Environment
I am using windows and the issue is m not able to install vonage server dependency as its not found in npm registry.

**Comment by isaacAssaban** [comment]
i am on mac and facing the same issue.

**Comment by JeremieDemarchez** [comment]
Same issue on WSL2. CICD is blocked by this problem, a quick fix would be great.

**Comment by manchuck** [comment]
Can you all post which version of the SDK you are trying to install? I'm able to install the SDK at version 3.0.20 without any issues. I do see that npmjs.com is not showing the `@vonage/audit` package however, I can use `npm show` and `npm install @vonage/audit@1.0.3` I will get in contact with npm to figure out why the package is not appearing.

**Comment by JeremieDemarchez** [comment]
The latest, simply run the following command to reproduce the problem (Linux system) : 
`mkdir testVonage && cd testVonage && npm init -y && npm install @vonage/server-sdk`

Are you able to reproduce the problem?

**Comment by JeremieDemarchez** [comment]
It seems to be solved, thank you. :)

**Comment by manchuck** [comment]
It appears that `3.0.11` of the SDK is causing the issue. Looking into it, TS failed to build for `@vonage/audit`, which meant that version was not published. I went back and corrected the build shortly after publishing. That seems like the most viable explanation on what happened

**Comment by mRahulRoy** [comment]
Can i install that server dependency now ?

**Comment by mRahulRoy** [comment]
https://dashboard.nexmo.com/getting-started/verify
verify user page in dashboard is also not working. Saying refresh or try again later

**Comment by mRahulRoy** [comment]
> It seems to be solved, thank you. :)

Yes, Now Its Working .
