### ISSUE TITLE
Latest beta release uses deprecated "request" package, which has an open CVE

### ISSUE THREAD

**Issue by jjtindale** [Vonage/vonage-node-sdk#807]
We use the beta release in order to gain access to the Conversation API functionality. From NPM, it looks like the latest beta release is [2.12.0-beta.3](https://www.npmjs.com/package/@vonage/server-sdk/v/2.12.0-beta.3). This release uses the deprecated [requests](https://github.com/request/request#deprecated) library, and this library has a [new CVE](https://github.com/advisories/GHSA-p8p7-x288-28g6). 

There is already [an issue](https://github.com/Vonage/vonage-node-sdk/issues/294) for removing `request`, but this is closed saying that the issue is no longer present, but it seems to still be an issue at least for the beta channel.

## Expected Behavior
I would expect the SDK to no longer use `request` as it has been deprecated since 2020.

## Current Behavior
The SDK uses `request` for the latest beta channel release.

## Possible Solution
Use a different HTTP library.

## Your Environment

* SDK Version: 2.12.0-beta.3
* Node Version: (e.g. Node 10.18): v16.19.1
* Operating System and version: MacOS, Github Actions.

**Comment by manchuck** [comment]
@jjtindale V3 of the SDK no longer uses `request` in favor of using `node-fetch`

Checkout the `3.x` branch for migration guides or feel free to reach out to our community slack if you have any other issue

**Comment by jjtindale** [comment]
Hi @manchuck, can I confirm that `3.x` supports the Conversation API? The `README.md` says it doesn't.

**Comment by manchuck** [comment]
@jjtindale Currently, V3 does not support the conversations API. We do have it in the roadmap to address this. In the meantime, you can use `@vonage/server-client` to call the conversations API. You will just need to extend the client class in order to set the authentication properly
