### ISSUE TITLE
I'm getting 411 error code randomly when creating a call.

### ISSUE THREAD

**Issue by witchmonster** [Vonage/vonage-node-sdk#81]
Voice API is returning 411 "length-required" code from time to time. Fixed by forking the nexmo library and including "Content-Length" header.

**Comment by cbetta** [comment]
@jkramr thank you for letting us know. Would you be able to open a pull request with the changes you made? We'd love to merge them in.

**Comment by witchmonster** [comment]
`// Fix broken due ot 411 Content-Length error now sent by Nexmo API`
 `// PL 2016-Sept-6 - commented out Content-Length 0`
 `// headers['Content-Length'] = 0;`
Uncommenting this solution does not work for me, as I receive `ReferenceError: headers is not defined`.
Specifying `'Content-Length': params.length` for each request although - does.
Creating a pull request shortly.

**Comment by cbetta** [comment]
Resolved by #82
