### ISSUE TITLE
How can I create new User with this SDK???

### ISSUE THREAD

**Issue by thethtetaung22** [Vonage/vonage-node-sdk#815]

**Comment by manchuck** [comment]
@thethtetaung22 V2 of the `server-sdk` is currently the only version that supports the conversation API. We do have a task in our backlog to port into V3. In the meantime, you can check out our documentation at https://developer.vonage.com/en/conversation/code-snippets/user/create-user, which has examples of how to use v2 of the SDK to interact with the conversations API.

Feel free to reach out in community Slack if you have any more questions
