### ISSUE TITLE
401 Error when sending Whats App message

### ISSUE THREAD

**Issue by manchuck** [Vonage/vonage-node-sdk#819]
When trying to send a WhatsApp Message, the authorization header does not appear to be sent. 

## Expected Behavior

The message should be sent with the correct authorization headers and the response should pass

## Current Behavior

The authorization header being sent is causing a 401 response.

## Steps to Reproduce (for bugs)

```js
    const res = await vonage.messages.send(new WhatsAppText({
        from: from,
        to: to,
        text: message,
      })
    );
```

## Your Environment

* SDK Version: `3.2.x` and `3.3.x`
* Node Version: (e.g. Node 10.18): 16 through 18
* Operating System and version: All

**Comment by dirk789** [comment]
I’m also experiencing it with SDK version 3.4.0 and Node 18 on MacOS. Is there any update or workaround on this?

**Comment by manchuck** [comment]
@dirk789 can you send over some example code? I found that It might just be a simple configuration issue

**Comment by SirPhemmiey** [comment]
I am using version `3.4.0`, but i can't see WhatsApp usage. Any heads up on that, please?

**Comment by manchuck** [comment]
@SirPhemmiey: Did you get a whats app business account from the Vonage Dashboard? You can find more information here: https://developer.vonage.com/en/messages/concepts/whatsapp

**Comment by manchuck** [comment]
Closing this issue as no new information was given, and the issue cannot be reproduced. Please open a new issue with example code if you continue to have an issue
