### ISSUE TITLE
error Couldn't find package "@vonage/verify2@^1.3.0" required by "@vonage/server-sdk@^3.0.12" on the "npm" registry.

### ISSUE THREAD

**Issue by masmerino13** [Vonage/vonage-node-sdk#829]
package install failing after traying to install
## Expected Behavior
the package to be installed properly

## Current Behavior
error Couldn't find package "@vonage/verify2@^1.3.0" required by "@vonage/server-sdk@^3.0.12" on the "npm" registry.

## Possible Solution
install the correct dependants

## Steps to Reproduce (for bugs)
yarn install @vonage/server-sdk

1.
1.
1.
1.

## Your Environment

* SDK Version:
* Node Version: (e.g. Node 10.18):
* Operating System and version:

**Comment by Come2Daddy** [comment]
Got the same problème with `@vonage/server-sdk@3.5.0` installs with `@3.4.0`.

**Comment by masmerino13** [comment]
@Come2Daddy yeah, looks like an issue with the latest version

**Comment by manchuck** [comment]
This has been resolved with patch `@vonage/server-sdk@3.5.1`. Sorry for the bad release
