### ISSUE TITLE
Add support for retrieving call recordings

### ISSUE THREAD

**Issue by leggetter** [Vonage/vonage-node-sdk#85]
For @jonlingard :)

Generally missing across the board on docs and in other libraries.

**Comment by gasp** [comment]
For the hasty ones.

```
const Nexmo = require('nexmo');
const fs = require('fs');
const https = require('https');
const nexmo = new Nexmo({
  apiKey: 'xxxx',
  apiSecret: 'xxxx',
  applicationId: 'xxxxx',
  privateKey: './private.key'
},{
  debug: true
});

const saveRecordings = (fileID, destFolder, callback) => {
  if (!fileID || typeof fileID != 'string') {
    throw new Error('"fileID" is a required parameter, and it should be a string');
  }
  var options = {
    host:'api.nexmo.com',
    path:`/v1/files/${fileID}`,
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${nexmo.generateJwt()}`
    }
  };
  const file = fs.createWriteStream(`${destFolder}/${fileID}.mp3`);
  var req = https.request(options, (res) => {
    console.log(`STATUS: ${res.statusCode}`);
    console.log(`HEADERS: ${JSON.stringify(res.headers)}`);
    res.pipe(file);
    res.on('end', () => callback(`${destFolder}/${fileID}.mp3`));
  });
  req.on('error', (e) => {
    console.log(`problem with request: ${e.message}`);
  });
  req.end();
};

saveRecordings('xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx', __dirname, (file) => {
  console.log(`The file was saved as ${file}`);
});
```

**Comment by leggetter** [comment]
@gasp `nexmo.generateJwt()` is supported though:
https://github.com/Nexmo/nexmo-node#jwt

**Comment by gasp** [comment]
Thanks @leggetter just updated the above snippet !

**Comment by cbetta** [comment]
Thanks @leggetter @gasp I'll add this to the library tomorrow

**Comment by girliemac** [comment]
👍 I was about to publish the Voice tutorial using fs to fetch the mp3, but I will wait! Basically, I did similar to @gasp, but used `request` module.

```
const request = require('request');

let url = 'https://api.nexmo.com/media/download?id=${fileID};
let jwt = Nexmo.generateJwt(__dirname + '/private.key', {application_id: appId});

request.get(url, {'auth': {'bearer': jwt}})
  .on('error', function(err) {
    console.log(err)
  })
  .pipe(fs.createWriteStream('${destFolder}/${fileID}.mp3'));
```

**Comment by cbetta** [comment]
@leggetter @girliemac @gasp so do we think the library needs to take care of writing to disk, or should it just return a buffer that the user can use to write the file to disk?

**Comment by cbetta** [comment]
Going off these docs: https://docs.nexmo.com/voice/voice-api/recordings

It seems that the webhook gets sent a `recording_url` after a recording. Few questions:

@girliemac why are you building the URL yourself? Where is `fileID` coming from in your case?
@gasp why are you using a seemingly different URL to load the recording from than @girliemac? Her's seems to match what is in the docs. Also where does the `fileID` come from in your case?

**Comment by gasp** [comment]
I think that the lib should handle the `fs` or else, its added value seems poor, something like
`nexmo.recordings.download(fileId, destinationPath, callback);`

@cbetta the fileID (or `file_uuid` to be consistent with `conversation_uuid`, `call_uuid`, `recording_uuid`...) is dirtily extracted from the webhook which provides a `recording_url` which looks like `https://api.nexmo.com/v1/file/11111111-2222-3333-4444-55555555` because my NCCO specifies

```
{
   "action": "record",
   "eventUrl": "https://my.super.api/recordings"
},
```
and I capture those events with
```
app.post('/recordings', (req, res) => {
  const conversation_uuid = req.body.conversation_uuid;
  const file_uuid = req.body.recording_url.substr(-36);
});
```

**Comment by cbetta** [comment]
@gasp so just to clarify, you extract the `file_uuid`, only to partially then reconstruct it again later to download the file?

See:

```js
const file_uuid = req.body.recording_url.substr(-36);
```

and 

```js
path:`/v1/files/${fileID}`,
```

**Comment by cbetta** [comment]
@gasp I'm asking as I'm wondering if it wouldn't be easier to instead do:

```js
nexmo.recordings.download(recordingUrl, destinationPath, callback);
```

**Comment by gasp** [comment]
I would prefer having `file_uuid` being the same as `recording_uuid`.

**Comment by cbetta** [comment]
Ok so for now my proposed implementation would be:

```js
nexmo.applications.download(recordingUrl, distinationPath, callback);
```

or 

```js
nexmo.recordings.download(recordingUrl, distinationPath, callback);
```

**Comment by leggetter** [comment]
@cbetta - it's likely that we should use `files` since to match the API resource that's being interacted with (`/v1/files` - which includes the version). As you can probably guess the plan is for this resource to offer more than just access to call recordings.

To be consistent with the other resources it should probably be a `get` function. So I'd suggest:

```js
nexmo.files.get(fileUUID, function(err, resp) {
  // resp is Buffer? I'm not sure how well the HttpClient class will handle this right now.
});
```

Since - as discussed - having to parse out the `fileUUID` is a pain `nexmo.files.get` could also accept a URL as the `fileUUID` parameter, check the format, and parse out the UUID.

**Comment by girliemac** [comment]
@cbetta yeah I am using the URL, "https://api.nexmo.com/media/download?id=xxxx" which I saw on the [doc](https://docs.nexmo.com/voice/voice-api/recordings), but the actual URL I get from the `recording_url` is the one with the version number. Both seem to work anyway.

and I do prefer `download` or something not `get` func name because we are actually using the file I/O and returning the buffer to save the mp3 file on the disk.

**Comment by leggetter** [comment]
I'm not against client libraries offering more intuitive and useful domain specific functionality e.g. offering file retrieval and saving via something like a `download`. But we should have a baseline of functionality that's common across all resources i.e. `get`, `create`, `update`, `delete` (where applicable).

**Comment by leggetter** [comment]
I've had confirmation we should be using `/v1/files` and not the media one. I'll get the doc updated too.

**Comment by cbetta** [comment]
Ok, for now I will implement 2 functions. 

```js
nexmo.files.get(fileUUID, function(err, resp) {
  // buffer or similar
});
```

```js
nexmo.files.save(fileUUID, filename, function(err, resp) {
  // callback with filename / size / etc?
});
```
