### ISSUE TITLE
[question] How to authenticate to the video package?

### ISSUE THREAD

**Issue by KayakinCoder** [Vonage/vonage-node-sdk#859]
We have a video application (tokbox.com) and previously used the project api key and secret for authentication in the sdk. 

It seems an application id and private key are needed for v3, although even that's unclear: https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/auth/README.md#options seems to indicate key/secret would work. Two questions:

1. Is api key + secret (values which can be found in the tokbox dashboard, when looking at a project) all that are needed for authentication, or is application id + private key required? When attempting to use api key + secret we get a "Error: Missing application id" following the simple create session example listed in the v3 blog announcement (https://developer.vonage.com/en/blog/announcing-the-vonage-node-sdk-v3-0-0), and I can open a separate issue for that if you'd want.

2. If application id + private key are needed, we haven't found any direction on how to get those values. We installed the CLI, tried `vonage config:set --apiKey=key_value --apiSecret=secret_value` with both the tokbox account-level key/secret and project-level key/secret, both of which throw an error when trying to run any command e.g. `vonage apps`
````
Error: Authentication Failure
Code: API_AUTH_ERR
````

**Comment by dragonmantank** [comment]
The Vonage Video SDK supplied in this repo is currently in a private beta, so therefore is not usable by the general public. We expect it to be available later this year. If you would like to use our Video API today, you can check out https://github.com/opentok/opentok-node instead (this is the exact same product, just using the older branding).

**Comment by KayakinCoder** [comment]
@dragonmantank 👍a notice on the readme and versioning 0.x.x would be good ways to let folks know that, so we don't waste a couple of hours trying to get it up and running
