### ISSUE TITLE
Request timeout option is still broken

### ISSUE THREAD

**Issue by jerwen** [Vonage/vonage-node-sdk#862]
Same issue as this [one](https://github.com/Vonage/vonage-node-sdk/issues/843)

Unfortunately the fix seems incomplete as from the client side, the timeout configuration option is explicitly set to null as you can see [here](https://github.com/Vonage/vonage-node-sdk/blob/e2a26981df85f4aecb1f9e708da096476ac7a47b/packages/server-client/lib/client.ts#L41).

**Comment by manchuck** [comment]
@jerwen Apologies for that. IDK how myself and @dragonmantank missed that. I published `3.9.2` of `@vonage/server-sdk` (`1.8.1` of `@vonage/server-client`) which is now checking the timeout parameter
