### ISSUE TITLE
readme example does not compile in TS

### ISSUE THREAD

**Issue by capaj** [Vonage/vonage-node-sdk#866]
## Expected Behavior
readme example in 
https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/server-client/README.md
 should compile in TS

## Current Behavior

![image](https://github.com/Vonage/vonage-node-sdk/assets/1305378/95e29a60-ed57-43b3-a98a-7ada959fd8d4)

## Possible Solution
not marking the Client class as abstract

## Steps to Reproduce (for bugs)
try to compile example code with TS

## Your Environment

* SDK Version: 
    "@vonage/server-client": "^1.8.2",
* Node Version: (e.g. Node 10.18): all of them
* Operating System and version: any

**Comment by manchuck** [comment]
@capaj #872 is a complete rework of our documentation. When that is released in early Jan, this issue should be resolved

**Comment by manchuck** [comment]
This should be resolved with version 3.12.0
