### ISSUE TITLE
Vonage.sms.verifySignature doesn't work with inbound SMS message

### ISSUE THREAD

**Issue by jjtindale** [Vonage/vonage-node-sdk#876]
Following [this guide](https://developer.vonage.com/en/getting-started/concepts/signing-messages) leads to an error in `verifySignature`.  This is because the inbound parameters are not all a string; some are nested JSON objects (e.g. `usage` and `sms`), and the library tries to call `.replace()` on these objects [here](https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/sms/lib/sms.ts#L63), leading to `TypeError: params[key].replace is not a function`.

``` javascript
{
    to: '<our vonage number>',
    from: '<my mobile number>',
    channel: 'sms',
    message_uuid: '<the uuid>',
    timestamp: '<the timestamp>',
    usage: { price: '<number>', currency: '<currency>' },
    message_type: 'text',
    text: '<the text>',
    context_status: 'none',
    sms: { num_messages: '1', count_total: '1' }
}
```

## Expected Behavior
`verifySignature` should work in the context of inbound SMS messages.

## Current Behavior
`TypeError: params[key].replace is not a function`

## Possible Solution
The solution depends on how the signature is meant to be calculated based on these nested fields.

## Steps to Reproduce (for bugs)

1. Call `new Vonage(new Auth(...)).sms.verifySignature()` using the object linked above as the request body (which is what you receive for the inbound SMS event webhook).
1. `TypeError: params[key].replace is not a function`

## Your Environment
* SDK Version: "@vonage/server-sdk": "^3.10.0"
* Node Version: (e.g. Node 10.18): v18.18.0
* Operating System and version: macOS 14.0

**Comment by manchuck** [comment]
@jjtindale Apologies for this. Our documentation site is going through a migration. It looks like the page regressed to demonstrate the V2 functionality. I have opened a ticket to get this updated as soon as possible. In the meantime, you can see the example in our code snippets [repo](https://github.com/Vonage/vonage-node-code-snippets/blob/master/messages/signed-webhooks/verify-signed-webhook.js)

**Comment by manchuck** [comment]
@jjtindale are you using the messages API? The payload looks like it is for the messages webhook

**Comment by manchuck** [comment]
@jjtindale If that is the case, you can follow this snippet here: https://github.com/Vonage/vonage-node-code-snippets/blob/master/messages/signed-webhooks/verify-signed-webhook.js

I will work with our team to clarify that page you posted

**Comment by manchuck** [comment]
@jjtindale The page and code snippet have been updated. Sorry for the inconvenience
