### ISSUE TITLE
Stream fails due to undefined method

### ISSUE THREAD

**Issue by yehya** [Vonage/vonage-node-sdk#88]
Streaming mp3 fails due to the method being undefined when it's supposed to be PUT

Output of debug when using stream

`info: Request: { host: 'api.nexmo.com',
  port: 443,
  path: '/v1/calls/-call-id/stream',
  method: undefined,
  headers: 
   { 'Content-Type': 'application/json',
     Accept: 'application/json',
     'User-Agent': 'nexmo-node/1.1.0/v4.6.1',
     'Content-Length': 81,
     Authorization: '--' } } 
Body: {"stream_url":["some.mp3"],"loop":1}
info: response ended: 400`

**Comment by cbetta** [comment]
@yehya I am trying to write a test for this before I merge your PR into master, woulld you be able to tell me what SDK call you made?

**Comment by cbetta** [comment]
Never mind, got it.

**Comment by yehya** [comment]
It was the audio streaming feature for MP3's into calls. Glad it worked, cheers!
(discovered this bug while building this btw! https://youtu.be/5IFfr-ggy-8?t=1619 )
