### ISSUE TITLE
[Bug]: Issue with npm install 

### ISSUE THREAD

**Issue by weisheng-homage** [Vonage/vonage-node-sdk#896]
### Node Version

18.x

### Platform

Mac (Apple Silcon)

### SDK Version

3.10.2

### Code Sample

sample repo here https://github.com/weisheng-homage/vonage_npm_broke/tree/main

### Expected Behavior

npm install to run fine

### Actual Behavior

see a bunch of error messages - i think the dependency is added wrongly for `@vonage/sms`

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @vonage/sms@^1.9.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by manchuck** [comment]
This was an issue with `@vonage/sms@1.9.2` not being published. This is now resolved. Sorry for the inconvenience
