### ISSUE TITLE
Update README to document what callback receives

### ISSUE THREAD

**Issue by robomotic** [Vonage/vonage-node-sdk#90]
[Edit by @cbetta]

Add documentation on what `callback` actually is. For most people it's clear to be a function but even then it would be good to document what to expect exactly.

[Original issue]

Hello there,
would it be possible to add the response to all function calls ?
Otherwise I am unable to determine if for example an SMS message was sent.

Cheers.

**Comment by cbetta** [comment]
@robomotic just trying to understand what you mean here. `sendSMS` accepts a callback that is called with an `error` and/or `response`, right? Is that not what you need?

**Comment by robomotic** [comment]
@cbetta I think a little clarification is required here, I assumed the callback was the webhook endpoint as described in the Nexmo documentation. It's just an unfortunate naming, perhaps adding a more complete code snippet would help ?

**Comment by cbetta** [comment]
@robomotic are you saying you just think the docs need updating?

**Comment by robomotic** [comment]
@cbetta Yes or an example to explain that callback is not the url callback . :-)

**Comment by radiodario** [comment]
It would be nice to see what arguments the callback is being sent, even if it follows the `(error, response)` convention, just for clarity's sake

**Comment by alexschwarz89** [comment]
Came here, (as a php developer) didn't know about (error, response) as a convention, solved my issue, but worth adding it do documentation, even if it's 2018. ;-)

**Comment by AlexLakatos** [comment]
Thanks for the feedback @alexschwarz89, I'll put it on my task list.

**Comment by tapz** [comment]
Looks like the docs have not yet been updated yet. 

After integrating to Twilio, I did the same to Nexmo. Very similar apis, but in Twilio "statusCallback" means a webhook url and in Nexmo "callback" means something undocumented, which after digging is something totally different than in Twilio. Also, the options too have a parameter called "callback", which is a webhook url. Really confusing. Both apis are also a bit outdated, as they should use promises.

The description of the options parameter points to the API documentation. As the options are a JavaScript object and API parameters names like "status-report-req" it's a bit unclear if the names should be converted to camel case or not.

**Comment by kellyjandrews** [comment]
This was added in this update - https://github.com/Nexmo/nexmo-node/commit/8ff1a5527b661453d212e99c27a77b8eff6a627d#diff-04c6e90faac2675aa89e2176d2eec7d8R72
