### ISSUE TITLE
How Do I:  connect 2 real phones?

### ISSUE THREAD

**Issue by Bambuuai** [Vonage/vonage-node-sdk#916]
### How do I

connect 2 real phones?

### API/Product

Voice

### Code Sample

I am going to make connection between 2 real phones using vonage platform.
How can I do this?
Thank you

**Comment by pardel** [comment]
See https://developer.vonage.com/en/api/conversation#createMember

**Comment by Bambuuai** [comment]
@pardel 
Thanks for your reply.

Could you explain more detail please? I'd like to know node code
