### ISSUE TITLE
[Bug]: Can not link vonage application with my VR phone number

### ISSUE THREAD

**Issue by fukemy** [Vonage/vonage-node-sdk#924]
### Node Version

16.x

### Platform

Mac (Apple Silcon)

### SDK Version

lasted

### Code Sample

vonage apps:link f5f961b7-27fd-474a-a705-52698cd744ae --number=6286660016  

### Expected Behavior

Hi, I am so sorry for ask a question in wrong place, But I can not find which place I can ask my question.

 I bought Vonage Business account, then I have a VR phone number like this: ***6660016, now I want to follow this guide to make a call:
 https://developer.vonage.com/en/voice/voice-api/guides/click-to-call?source=voice
 
  But I stuck at link a phone number with my Application, in this step:
`vonage apps:link ***961b7-27fd-474a-a705-52698cd744ae --number=***6660016`, then I got error:

TypeError: Cannot read properties of undefined (reading '0')

I need your help please, I just learning Vonage API, if I ask a question in wrong place, please guide me where the place to ask

### Actual Behavior

<img width="800" alt="Ảnh màn hình 2024-03-13 lúc 10 38 11" src="https://github.com/Vonage/vonage-node-sdk/assets/8202437/274ba29b-38cc-41d9-91f2-e4a90ba980ec">
Here is screenshoot

**Comment by pardel** [comment]
@fukemy the phone number needs to include the country code and be in the E164 format. See this page for more info:
https://developer.vonage.com/en/getting-started/concepts/glossary#e164-format

@manchuck even though the number was invalid, this looks like a CLI not handling the error case properly.

**Comment by fukemy** [comment]
Hi @pardel, thanks for fast reply, the number is from Vonage Business VR number that we bought, do you mean this not working to Vonage app:link function? Sorry for my silli question, I am new to Vonage:
<img width="1512" alt="Ảnh màn hình 2024-03-13 lúc 16 22 41" src="https://github.com/Vonage/vonage-node-sdk/assets/8202437/51c9076f-b21f-4953-9512-24b539a8fe33">

**Comment by pardel** [comment]
@fukemy ah - that is an US number and needs to be prefixed by a "1" to fullfil the E164 requirement. However, those numbers can't be linked to a Vonage applications. Only numbers purchased inside your Vonage account can - they can be found here: https://dashboard.nexmo.com/your-numbers

**Comment by fukemy** [comment]
> @fukemy ah - that is an US number and needs to be prefixed by a "1" to fullfil the E164 requirement. However, those numbers can't be linked to a Vonage applications. Only numbers purchased inside your Vonage account can - they can be found here: https://dashboard.nexmo.com/your-numbers

thanks you so much I will try developer number

**Comment by manchuck** [comment]
@pardel I will open an issue in CLI to address the validation issue

**Comment by manchuck** [comment]
Closing this issue. The error handling for the CLI will be updated as we work on v2 of the CLI
