### ISSUE TITLE
[Bug]: Differences between documentation and implementation

### ISSUE THREAD

**Issue by ThingUroboros** [Vonage/vonage-node-sdk#925]
### Node Version

20.x

### Platform

Docker Container

### SDK Version
@vonage/voice@1.11.1

### Code Sample

...
```
  'af', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'ar', // 
  'bg', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'bn', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'ca', //
  'cmn', //
  'cs', //
  'cy', //
  'da', //
  'de', //
  'el', //
  'en', //
  'es', //
  'eu', //
  'fi', //
  'fil', //
  'fr', //
  'gl', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'gu', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'he', //
  'hi', //
  'hu', //
  'id', //
  'is', //
  'it', //
  'ja', //
  'kn', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'ko', // 
  'lv', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'ml', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'ms', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'nb', //
  'nl', //
  'no', //
  'pa', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'pl', //
  'pt', //
  'ro', //
  'ru', //
  'sk', // 
  'sr', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'sv', //
  'ta', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'te', // missing https://github.com/Vonage/vonage-node-sdk/blob/%40vonage/voice%401.11.1/packages/voice/lib/enums/TTSLanguages.ts
  'th', //
  'tr', //
  'uk', //
  'vi', //
  'yue', //
```

### Expected Behavior

I have come across discrepancies in the documentation regarding language support in the library's.
What should I base it on?

https://developer.vonage.com/en/voice/voice-api/concepts/text-to-speech#supported-languages
https://github.com/nexmo-community/vapi-tts-voices/blob/main/voices.json
https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/voice/lib/enums/TTSLanguages.ts

### Actual Behavior

I don't know.

**Comment by manchuck** [comment]
@ThingUroboros We continue to keep adding new TTS voices. The enum to help ensure the correct voice/language is passed in. You should be able to pass in any string you like with out any issues.  Are you having a hard time compiling? If not, then the next time we do work on the voice package, we will update the list.

**Comment by ThingUroboros** [comment]
@manchuck 
The error lies in the type of the 'language' parameter.

<img width="666" alt="Snímek obrazovky 2024-03-20 v 23 08 51" src="https://github.com/Vonage/vonage-node-sdk/assets/20670108/56e5cd2f-6788-4784-94f7-a312092de419">

```
NCCOAction 
...
language?: TTSLanguages | undefined
...

export type TalkAction = {
    action: NCCOActions.TALK;
    text: string;
    bargeIn?: boolean;
    loop?: number;
    level?: string;
    language?: TTSLanguages;
    style?: string;
    premium?: boolean;
};
```

**Comment by ThingUroboros** [comment]
I can make a pull request.
But I probably don't have the permission.

```
remote: Permission to Vonage/vonage-node-sdk.git denied to ThingUroboros.
fatal: unable to access 'https://github.com/Vonage/vonage-node-sdk.git/': The requested URL returned error: 403
```

[TTSLanguages.ts.zip](https://github.com/Vonage/vonage-node-sdk/files/14696214/TTSLanguages.ts.zip)

**Comment by manchuck** [comment]
@ThingUroboros I will update the type to accept either the enum or a string to avoid this problem. We are constantly adding languages faster than we can deploy new updates to this list.

**Comment by manchuck** [comment]
@ThingUroboros `v3.14.1` of the `@vonage/server-sdk` (`v1.12.1` of `@vonage/voice`) has been released with these languages update
