### ISSUE TITLE
[Bug]: No matching version found for @vonage/conversations@^1.3.0.

### ISSUE THREAD

**Issue by mathieuPaczesny** [Vonage/vonage-node-sdk#945]
### Node Version

20.x

### Platform

Mac (Apple Silcon)

### SDK Version

3.15.0

### Code Sample

npm i --save @vonage/server-sdk

npm error code ETARGET
npm error notarget No matching version found for @vonage/conversations@^1.3.0.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.

### Expected Behavior

Install the SDK

### Actual Behavior

I’ve tried numerous versions but I still have this problem. It suddenly occurred yesterday during the installation of one of my Firebase functions. I’ve never had issues like this before.”

**Comment by VareTom** [comment]
Hello, I noticed this morning that I also have the problem :

```
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @vonage/conversations@^1.3.0
This error happened while installing the dependencies of @vonage/server-sdk@3.15.0
The latest release of @vonage/conversations is "1.2.1".
```

Thanks :)

**Comment by manchuck** [comment]
Apologies. The conversations package failed to publish yesterday when I deployed the new message update. The OTP timed out and I missed the error when publishing
