### ISSUE TITLE
[Bug]: Switch to ESM breaks existing applications

### ISSUE THREAD

**Issue by mdybich** [Vonage/vonage-node-sdk#950]
### Node Version

18.x

### Platform

Mac (Apple Silcon)

### SDK Version

3.15.1

### Code Sample

import { Vonage } from '@vonage/server-sdk';

### Expected Behavior

The import should work for applications that do not use ESM modules.

### Actual Behavior

After the change made yesterday ([commit e361fbe](https://github.com/Vonage/vonage-node-sdk/commit/e361fbe755ee5bd4b264e5f7e41900624c7d9f25)), all of the packages have been switched to use [ECMAScript Modules](https://webpack.js.org/guides/ecma-script-modules/). This is a breaking change for projects that are not using ESM modules. I believe such a change should be made only in major versions (following semantic versioning).

**Comment by mdybich** [comment]
Downgrading @vonage/server-sdk will not help because [carets](https://github.com/Vonage/vonage-node-sdk/blob/3.x/packages/server-sdk/package.json#L41-L58) are used under the hood, so it will always get the latest version (with ESM modules enabled).

**Comment by RadhaHariharanEdvak** [comment]
Is there any update on this issue.

**Comment by thanatos11** [comment]
any news?

**Comment by manchuck** [comment]
Apologies for this I'm working on adjusting the TS compiler to output both CJS and ESM module formats

**Comment by manchuck** [comment]
This has been resolved with the next minor version of the SDK (v3.16.0). I left in some TS compiler options that only focused on ESM to remove the need to have Bable for testing. Apologies again for this error. 

@mdybich I will update the packages to use strict versions instead of carets to allow for easier downgrading
