### ISSUE TITLE
[Bug]: Users Update should be PATCH not PUT

### ISSUE THREAD

**Issue by abdulajet** [Vonage/vonage-node-sdk#951]
### Node Version

22.x

### Platform

Mac (Apple Silcon)

### SDK Version

3.16.0

### Code Sample

vonageUser = await vonage.users.updateUser({ id: userId, imageUrl: imageUrl });

### Expected Behavior

To PATCH
https://developer.vonage.com/en/api/application.v2#updateUser

### Actual Behavior

Makes PUT request

**Comment by manchuck** [comment]
Fixed in #953 Will be pushed with next release
