### ISSUE TITLE
How Do I: Authenticate to send a whatsapp message?

### ISSUE THREAD

**Issue by josedugu** [Vonage/vonage-node-sdk#957]
### How do I

send a whastapp message

### API/Product

Messages

### Code Sample

```js
import { Auth } from '@vonage/auth';
import { WhatsAppText, Messages } from '@vonage/messages';

const messagesClient = new Messages(
  new Auth({
    apiKey: 'API_KEY',
    apiSecret: 'API_SECRET',
  })
);

export const sendVonageWhatsappMessageWithVonageSdk = async () => {
  console.log('SENDING MESSAGE');
  const message = await messagesClient.send(
    new WhatsAppText({
      to: 'CUSTOMER_NUMBER',
      from: 'CLIENT_NUMBER',
      text: 'Hi',
      clientRef: 'my-personal-reference',
    })
  );
  console.log('message sent', message);
  return message;
};

sendVonageWhatsappMessageWithVonageSdk();
```

No matter what kind of parameter I passed on new Auth, I am always getting 401 unauthorized, I also tried using JWT but not working. 

![image](https://github.com/user-attachments/assets/421b9aa1-f193-41b8-9367-6304bab3bea3)

This is package json

{
    "type": "module",
    "dependencies": {
        "@vonage/auth": "^1.12.0",
        "@vonage/jwt": "^1.11.0",
        "@vonage/messages": "^1.16.0"
    }
}

**Comment by manchuck** [comment]
@josedugu The messages API does not use `apiKey` and `apiSecret` but rather uses `applicationId` and `privateKey`. You can see an example of this in our code snippets repository: https://github.com/Vonage/vonage-node-code-snippets/blob/main/messages/whatsapp/send-text.js

Our documentation site can get you started on how to setup an application in your dashboard along with connecting your WhatsApp Business Account to that application: https://developer.vonage.com/en/messages/concepts/whatsapp
