### ISSUE TITLE
[Bug]: Types for @vonage/media-processor not resolved when using moduleResolution "node16"

### ISSUE THREAD

**Issue by danewilson** [Vonage/vonage-node-sdk#969]
### Node Version

20.x

### Platform

Mac (Apple Silcon)

### SDK Version

n/a

### Code Sample

tsconfig.json
```json
{
  "compilerOptions": {
    "module": "node16",
    "moduleResolution": "node16"
  }
}
```

index.ts
```ts
import { MediaProcessor } from '@vonage/media-processor'
```

### Expected Behavior

No type errors.

### Actual Behavior

> TS7016: Could not find a declaration file for module '@vonage/media-processor'. '/Users/username/repo/node_modules/@vonage/media-processor/dist/media-processor.es.js' implicitly has an 'any' type.
  There are types at '/Users/username/repo/node_modules/@vonage/media-processor/dist/types/lib/main.d.ts', but this result could not be resolved when respecting package.json "exports". The '@vonage/media-processor' library may need to update its package.json or typings.

TypeScript is trying to resolve the types from package.json:exports ([docs](https://www.typescriptlang.org/docs/handbook/modules/reference.html#packagejson-exports)) because `moduleResolution` is `node16`, but they are in a different location so it can't find them automatically. You need to specify them for both `import` and `require` like this:

```diff
 "types": "./dist/types/lib/main.d.ts",
 "main": "./dist/media-processor.umd.js",
 "module": "./dist/media-processor.es.js",
 "exports": {
   ".": {
-    "import": "./dist/media-processor.es.js",
-    "require": "./dist/media-processor.umd.js"
+    "import": {
+      "types": "./dist/types/lib/main.d.ts",
+      "default": "./dist/media-processor.es.js"
+    },
+    "require": {
+      "types": "./dist/types/lib/main.d.ts",
+      "default": "./dist/media-processor.umd.js"
+    }
   }
 }
```

I realise `@vonage/media-processor` is not part of this SDK but the repository listed for it (https://github.com/Vonage/vonage-media-transformers-samples) doesn't seem like a suitable place to raise an issue, and I was hoping it would get more visibility here.

**Comment by manchuck** [comment]
@danewilson Yes, this is not the place to report this bug. You can report this in the repo or contact support if you still have issues.

Apologizes that I cannot be more help.
